/**
 * Dynamo
 * Toggle: PBAoE, DoT (Energy), Foe -End
 *
 * Source: blaster_support/electricity_manipulation/lightning_clap.json
 */

import type { Power } from '@/types';

export const Dynamo: Power = {
  "name": "Dynamo",
  "internalName": "Lightning_Clap",
  "available": 19,
  "description": "While active, you regenerate health and recover endurance very quickly. Overflow energy generated by this power can damage all nearby foes.",
  "shortHelp": "Toggle: PBAoE, DoT (Energy), Foe -End",
  "icon": "electricitymanipulation_lightningfield.png",
  "powerType": "Toggle",
  "targetType": "Self",
  "effectArea": "AoE",
  "stats": {
    "accuracy": 1,
    "radius": 20,
    "recharge": 10,
    "castTime": 2.03,
    "maxTargets": 10
  },
  "allowedEnhancements": [
    "EnduranceModification",
    "Recharge",
    "Healing",
    "Damage",
    "Accuracy"
  ],
  "allowedSetCategories": [
    "Blaster Archetype Sets",
    "Endurance Modification",
    "Healing",
    "Melee AoE Damage",
    "Universal Damage Sets"
  ],
  "maxSlots": 6,
  "damage": [
    {
      "type": "Energy",
      "scale": 0.17,
      "table": "Melee_Damage"
    },
    {
      "type": "Energy",
      "scale": 0.1382,
      "table": "Melee_PvPDamage"
    }
  ],
  "effects": {
    "enduranceDrain": {
      "scale": 1,
      "table": "Melee_EndDrain"
    }
  }
};
