// AUTO-GENERATED by scripts/build-engine.mjs — do not hand-edit. Content hash of each
// contract bundle, appended to its fetch URL by engine.ts so an HTTP-cached bundle can
// never be served to a .wasm built against a different schema. Workbox is told to ignore
// the `v` parameter (vite.config.ts `ignoreURLParametersMatching`), so the precached
// entry still matches and offline loads are unaffected.

export const ENGINE_BUNDLE_VERSIONS: Record<string, string> =
  {
    "brainstorm": "6e271615d7874f00",
    "homecoming": "49ed2ffca1304dd1",
    "rebirth": "cd6c171985c2e96e",
    "thunderspy": "11129f48fd44a4f6"
  };
