// AUTO-GENERATED by scripts/build-engine.mjs — do not hand-edit. Content hash of each
// contract bundle, appended to its fetch URL by engine.ts so an HTTP-cached bundle can
// never be served to a .wasm built against a different schema. Workbox is told to ignore
// the `v` parameter (vite.config.ts `ignoreURLParametersMatching`), so the precached
// entry still matches and offline loads are unaffected.

export const ENGINE_BUNDLE_VERSIONS: Record<string, string> =
  {
    "homecoming": "c9968370175efead",
    "rebirth": "20d1af3aa863650c",
    "thunderspy": "f3e4c9852378ed8f"
  };
