/**
 * Calculation utilities barrel export
 */

// Damage calculation
export {
  getBaseDamage,
  calculateActualDamage,
  calculatePowerDamage,
  calculateDotDamage,
  formatDamage,
  calculateBuffDebuffValue,
  type DamageTableType,
  type DamageCalculationOptions,
  type PowerDamageResult,
  type DotDamageResult,
  type DamageEffect,
  type PowerWithDamage,
  type BuildContext,
} from './damage';

// Enhancement values
export {
  getAspectSchedule,
  getIOValueAtLevel,
  normalizeAspectName,
  applyED,
  parseIOSetPieceValues,
  calculatePowerEnhancementBonuses,
  calculateCommonIOValue,
  formatEnhancementValue,
  type EnhancementSchedule,
  type ParsedBonuses,
  type SlotWithEnhancement,
  type PowerWithSlots,
  type EnhancementBonuses,
} from './enhancement-values';

// Power stats
export {
  calculatePowerStats,
  formatStatForTooltip,
  isStatEnhanced,
  hasGlobalBonuses,
  calculateImprovement,
  type ThreeTierStat,
  type ComplexStat,
  type DamageScale,
  type PowerEffectsForCalc,
  type PowerForCalc,
  type GlobalBonuses,
  type PowerStats,
} from './power-stats';

// Set bonuses (Rule of 5)
export {
  normalizeStatName,
  createBonusTracking,
  trackBonus,
  getAggregatedFromTracking,
  collectAllSetBonuses,
  calculateSetBonuses,
  getStatBreakdown,
  isBonusCapped,
  getBonusCount,
  getActiveSetBonusesList,
  type BonusSource,
  type ValueTracking,
  type BonusTracking,
  type AggregatedBonuses,
  type StatBreakdownItem,
  type IOSet,
  type BuildPowers,
} from './set-bonuses';

// Character stats
export {
  STAT_CATEGORIES,
  DEFAULT_ENABLED_STATS,
  createEmptyStats,
  getBaselineEndurance,
  getBaselineRecovery,
  getBaselineHealth,
  calculatePoolPowerBonuses,
  calculateActivePowerBonuses,
  formatStatValue,
  STAT_TO_COMBINED,
  applyStatToCharacter,
  type StatDefinition,
  type StatCategory,
  type CharacterStats,
  type BaselineHealth,
  type PowerBonuses,
  type ActivePowerBonuses,
  type FormattedStat,
} from './stats';

// Character totals (unified calculation system)
export {
  calculateCharacterTotals,
  getBreakdownForStat,
  hasStatBonuses,
  getAlphaEnhancementBonuses,
  type GlobalBonuses as CharacterGlobalBonuses,
  type StatSource,
  type DashboardStatBreakdown,
  type CharacterCalculationResult,
} from './character-totals';

// AT-based effect calculations (using Homecoming tables)
export {
  calculateScaledEffect,
  calculateMultipleEffects,
  calculateScaledDamage,
  calculatePowerDamageFromScaled,
  sumDamageResults,
  calculateScaledHeal,
  isScaledEffect,
  normalizeTableName,
  normalizeArchetypeId,
  getArchetypeTableNames,
  hasATTables,
  compareATModifiers,
  formatEffectValue,
  formatDamageValue,
  type ScaledEffect,
  type ScaledDamage,
  type EffectCalculationResult,
  type DamageCalculationResult as ATDamageResult,
} from './at-effects';

// Archetype inherent calculations
export {
  calculateDefiance,
  isBlasterAttackPower,
  getDominationInfo,
  calculateDominationMagnitude,
  calculateDominationDuration,
  isDominatorControlPower,
  DOMINATION_MEZ_PROTECTION,
  getScourgeInfo,
  calculateScourgeChance,
  calculateScourgeDamage,
  isCorruptorAttackPower,
  getFuryInfo,
  calculateFuryDamageBonus,
  calculateFuryDamage,
  isBruteAttackPower,
  getSupremacyInfo,
  getBodyguardInfo,
  calculateSupremacyDamage,
  calculateSupremacyToHit,
  calculateBodyguardDamage,
  isMastermindPower,
  getVigilanceInfo,
  calculateVigilanceDamageBonus,
  calculateVigilanceDamage,
  isDefenderPower,
  getOpportunityInfo,
  isSentinelPower,
  getCriticalHitInfo,
  calculateCriticalHitChance,
  calculateCriticalHitDamage,
  isScrapperAttackPower,
  getAssassinationInfo,
  calculateAssassinationCritChance,
  calculateAssassinationDamageBonus,
  calculateAssassinationDamage,
  isStalkerAttackPower,
  getGauntletInfo,
  calculateGauntletRadius,
  calculateGauntletArc,
  isTankerPower,
  getContainmentInfo,
  calculateContainmentDamageBonus,
  calculateContainmentDamage,
  isControllerPower,
  type DefianceInfo,
  type DominationInfo,
  type DominationMezType,
  type ScourgeInfo,
  type FuryInfo,
  type SupremacyInfo,
  type BodyguardInfo,
  type VigilanceInfo,
  type OpportunityInfo,
  type CriticalHitInfo,
  type CriticalHitTarget,
  type AssassinationInfo,
  type GauntletInfo,
  type ContainmentInfo,
  type ContainmentMezType,
} from './inherents';
