/**
 * Script to convert legacy powersets and power pools to TypeScript-compatible format
 *
 * Run with: node scripts/convert-powers.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ============================================
// POWERSET CONVERSION
// ============================================

function convertPowersets() {
  const legacyDir = path.join(__dirname, '../legacy/js/data/powersets');
  const outputPath = path.join(__dirname, '../src/data/powersets-raw.ts');

  console.log('Converting powersets...');

  const powersets = {};

  // Walk through archetype directories
  const archetypeDirs = fs.readdirSync(legacyDir);

  for (const archetype of archetypeDirs) {
    const archetypePath = path.join(legacyDir, archetype);
    if (!fs.statSync(archetypePath).isDirectory()) continue;

    const powersetFiles = fs.readdirSync(archetypePath).filter((f) => f.endsWith('.js'));

    for (const file of powersetFiles) {
      const filePath = path.join(archetypePath, file);
      const content = fs.readFileSync(filePath, 'utf-8');

      // Extract the powerset object - look for const NAME = { ... };
      const match = content.match(/const\s+\w+\s*=\s*(\{[\s\S]*?\n\});/);
      if (!match) {
        console.warn(`  Could not parse: ${archetype}/${file}`);
        continue;
      }

      try {
        let powerset;
        eval(`powerset = ${match[1]}`);

        // Generate ID from archetype and filename
        const powersetName = file.replace('.js', '');
        const id = `${archetype}/${powersetName}`;

        powersets[id] = powerset;
      } catch (e) {
        console.warn(`  Error parsing ${archetype}/${file}: ${e.message}`);
      }
    }
  }

  console.log(`Found ${Object.keys(powersets).length} powersets`);

  // Count by archetype
  const archetypeCounts = {};
  for (const id of Object.keys(powersets)) {
    const archetype = id.split('/')[0];
    archetypeCounts[archetype] = (archetypeCounts[archetype] || 0) + 1;
  }
  console.log('Powersets by archetype:', archetypeCounts);

  // Generate TypeScript output
  const tsContent = `/**
 * Raw Powerset data
 * Auto-generated from legacy/js/data/powersets/
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * Run: node scripts/convert-powers.js
 *
 * Total powersets: ${Object.keys(powersets).length}
 * Archetypes: ${JSON.stringify(archetypeCounts)}
 */

export const POWERSETS_RAW = ${JSON.stringify(powersets, null, 2)} as const;
`;

  fs.writeFileSync(outputPath, tsContent, 'utf-8');
  console.log(`Written to ${outputPath}`);
}

// ============================================
// POWER POOL CONVERSION
// ============================================

function convertPowerPools() {
  const legacyDir = path.join(__dirname, '../legacy/js/data/pools');
  const outputPath = path.join(__dirname, '../src/data/power-pools-raw.ts');

  console.log('\nConverting power pools...');

  const pools = {};

  const poolFiles = fs.readdirSync(legacyDir).filter((f) => f.endsWith('.js'));

  for (const file of poolFiles) {
    const filePath = path.join(legacyDir, file);
    const content = fs.readFileSync(filePath, 'utf-8');

    // Extract the pool object
    const match = content.match(/const\s+POOL_\w+\s*=\s*(\{[\s\S]*?\n\});/);
    if (!match) {
      console.warn(`  Could not parse: ${file}`);
      continue;
    }

    try {
      let pool;
      eval(`pool = ${match[1]}`);

      pools[pool.id] = pool;
    } catch (e) {
      console.warn(`  Error parsing ${file}: ${e.message}`);
    }
  }

  console.log(`Found ${Object.keys(pools).length} power pools`);
  console.log('Pools:', Object.keys(pools).join(', '));

  // Generate TypeScript output
  const tsContent = `/**
 * Raw Power Pool data
 * Auto-generated from legacy/js/data/pools/
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * Run: node scripts/convert-powers.js
 *
 * Total pools: ${Object.keys(pools).length}
 * Pool IDs: ${JSON.stringify(Object.keys(pools))}
 */

export const POWER_POOLS_RAW = ${JSON.stringify(pools, null, 2)} as const;
`;

  fs.writeFileSync(outputPath, tsContent, 'utf-8');
  console.log(`Written to ${outputPath}`);
}

// ============================================
// MAIN
// ============================================

console.log('Converting power data...\n');
convertPowersets();
convertPowerPools();
console.log('\nDone!');
