/**
 * Script to convert legacy io-sets.js to TypeScript-compatible format
 *
 * Run with: node scripts/convert-io-sets.js [--dataset <id>]
 *
 * Note: this reads from `legacy/js/data/io-sets.js` which is no longer
 * shipped in this repo — the live IO set data now comes from boostsets.bin
 * via the bin-crawler pipeline. Kept here for historical re-runs.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// `--dataset <id>` flag — IO sets now live under
// `src/data/datasets/<id>/io-sets-raw.ts`.
function parseDatasetArg(argv) {
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--dataset' && i + 1 < argv.length) return argv[i + 1];
    if (argv[i].startsWith('--dataset=')) return argv[i].slice('--dataset='.length);
  }
  return 'homecoming';
}
const datasetId = parseDatasetArg(process.argv);

// Read the legacy file
const legacyPath = path.join(__dirname, '../legacy/js/data/io-sets.js');
const outputPath = path.join(__dirname, `../src/data/datasets/${datasetId}/io-sets-raw.ts`);

console.log('Reading legacy IO sets data...');
const legacyContent = fs.readFileSync(legacyPath, 'utf-8');

// Extract the object from the JS file
// The file defines: const IO_SETS = { ... };
const match = legacyContent.match(/const IO_SETS = (\{[\s\S]*\});?\s*$/);
if (!match) {
  console.error('Could not find IO_SETS object in legacy file');
  process.exit(1);
}

// Parse the object
let ioSets;
try {
  // Use eval to parse the JS object (safe since we control the input file)
  eval(`ioSets = ${match[1]}`);
} catch (e) {
  console.error('Failed to parse IO_SETS object:', e.message);
  process.exit(1);
}

console.log(`Found ${Object.keys(ioSets).length} IO sets`);

// Patch unique flags from raw Homecoming data
// The legacy data often has unique:false for pieces that have unique_group constraints
const rawDir = path.join(__dirname, '../raw_data_homecoming-raw_data_homecoming-20251209_7415/boost_sets');
if (fs.existsSync(rawDir)) {
  console.log('Patching unique flags from raw Homecoming data...');
  let patchCount = 0;
  const rawFiles = fs.readdirSync(rawDir).filter(f => f.endsWith('.json'));
  for (const file of rawFiles) {
    const data = JSON.parse(fs.readFileSync(path.join(rawDir, file), 'utf-8'));
    const boostInfos = data.computed?.boost_infos;
    if (!boostInfos || !data.boost_lists) continue;

    const setKey = file.replace('.json', '');
    const set = ioSets[setKey];
    if (!set) continue;

    // Map boost key -> piece num (1-based)
    const boostToPieceNum = {};
    for (let i = 0; i < data.boost_lists.length; i++) {
      for (const entry of data.boost_lists[i]) {
        const parts = entry.split('.');
        if (parts.length >= 2) boostToPieceNum[parts[1].toLowerCase()] = i + 1;
      }
    }

    for (const [key, info] of Object.entries(boostInfos)) {
      if (key.startsWith('crafted_') && info.unique_group?.length > 0) {
        const pieceNum = boostToPieceNum[key];
        const piece = set.pieces?.find(p => p.num === pieceNum);
        if (piece && !piece.unique) {
          piece.unique = true;
          patchCount++;
        }
      }
    }
  }
  console.log(`  Patched ${patchCount} pieces with unique flag`);
}

// Count by category
const categories = {};
for (const set of Object.values(ioSets)) {
  categories[set.category] = (categories[set.category] || 0) + 1;
}
console.log('Categories:', categories);

// Generate TypeScript output
const tsContent = `/**
 * Raw IO Set data
 * Auto-generated from legacy/js/data/io-sets.js
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * Run: node scripts/convert-io-sets.js
 *
 * Total sets: ${Object.keys(ioSets).length}
 * Categories: ${JSON.stringify(categories)}
 */

// Type definition for legacy format (used by io-sets.ts transformer)
interface LegacyIOSetPiece {
  num: number;
  name: string;
  aspects: string[];
  proc: boolean;
  unique: boolean;
}

interface LegacySetBonusEffect {
  stat: string;
  value: number;
  desc: string;
}

interface LegacySetBonus {
  pieces: number;
  effects: LegacySetBonusEffect[];
}

interface LegacyIOSet {
  name: string;
  category: string;
  type: string;
  minLevel: number;
  maxLevel: number;
  bonuses: LegacySetBonus[];
  pieces: LegacyIOSetPiece[];
  icon: string;
}

type LegacyIOSetRegistry = Record<string, LegacyIOSet>;

export const IO_SETS_RAW: LegacyIOSetRegistry = ${JSON.stringify(ioSets, (key, value) => typeof value === 'number' ? Math.round(value * 10000) / 10000 : value, 2)};
`;

fs.writeFileSync(outputPath, tsContent, 'utf-8');
console.log(`Written to ${outputPath}`);
console.log('Done!');
