/**
 * Script to convert legacy io-sets.js to TypeScript-compatible format
 *
 * Run with: node scripts/convert-io-sets.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read the legacy file
const legacyPath = path.join(__dirname, '../legacy/js/data/io-sets.js');
const outputPath = path.join(__dirname, '../src/data/io-sets-raw.ts');

console.log('Reading legacy IO sets data...');
const legacyContent = fs.readFileSync(legacyPath, 'utf-8');

// Extract the object from the JS file
// The file defines: const IO_SETS = { ... };
const match = legacyContent.match(/const IO_SETS = (\{[\s\S]*\});?\s*$/);
if (!match) {
  console.error('Could not find IO_SETS object in legacy file');
  process.exit(1);
}

// Parse the object
let ioSets;
try {
  // Use eval to parse the JS object (safe since we control the input file)
  eval(`ioSets = ${match[1]}`);
} catch (e) {
  console.error('Failed to parse IO_SETS object:', e.message);
  process.exit(1);
}

console.log(`Found ${Object.keys(ioSets).length} IO sets`);

// Count by category
const categories = {};
for (const set of Object.values(ioSets)) {
  categories[set.category] = (categories[set.category] || 0) + 1;
}
console.log('Categories:', categories);

// Generate TypeScript output
const tsContent = `/**
 * Raw IO Set data
 * Auto-generated from legacy/js/data/io-sets.js
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * Run: node scripts/convert-io-sets.js
 *
 * Total sets: ${Object.keys(ioSets).length}
 * Categories: ${JSON.stringify(categories)}
 */

// Type definition for legacy format (used by io-sets.ts transformer)
interface LegacyIOSetPiece {
  num: number;
  name: string;
  aspects: string[];
  proc: boolean;
  unique: boolean;
}

interface LegacySetBonusEffect {
  stat: string;
  value: number;
  desc: string;
}

interface LegacySetBonus {
  pieces: number;
  effects: LegacySetBonusEffect[];
}

interface LegacyIOSet {
  name: string;
  category: string;
  type: string;
  minLevel: number;
  maxLevel: number;
  bonuses: LegacySetBonus[];
  pieces: LegacyIOSetPiece[];
  icon: string;
}

type LegacyIOSetRegistry = Record<string, LegacyIOSet>;

export const IO_SETS_RAW: LegacyIOSetRegistry = ${JSON.stringify(ioSets, null, 2)};
`;

fs.writeFileSync(outputPath, tsContent, 'utf-8');
console.log(`Written to ${outputPath}`);
console.log('Done!');
