/**
 * Full data regeneration orchestrator.
 *
 * Rebuilds all Node-converter output from the committed `exported_powers/` input
 * (no .pigg / no Python needed), for one or all datasets, in dependency order.
 * This is the single entrypoint the "regen-and-diff" CI guard runs: because the
 * converters embed no timestamps or other non-determinism, a clean working tree
 * before this runs must remain clean after — any diff means the committed output
 * drifted from what the current converters produce.
 *
 * Usage:
 *   node scripts/regen-all.cjs                     # full rebuild, both datasets
 *   node scripts/regen-all.cjs --dataset rebirth   # full rebuild, one dataset
 *   node scripts/regen-all.cjs --generated-only    # only src/data/.../generated/
 *                                                  # (what the CI diff checks)
 *
 * NOT covered (separate pipelines, intentionally excluded):
 *   - IO sets — generated by `extract-rebirth-io-sets-v2.py --dataset <id>`
 *     (both homecoming and rebirth) directly from `boostsets.bin` + `powers.bin`
 *     in the .pigg archives. Python/pigg dependency; writes io-sets-raw.ts, not
 *     generated/. Regenerate manually when boostsets change. (The old
 *     convert-io-sets.js / extract-rebirth-io-sets.cjs predecessors are retired.)
 *   - reconvert-redirect-powersets.cjs — a stale one-off migration (old `powers/`
 *     layout); redirect powersets are handled by convert-all-powersets normally.
 */

const { execSync } = require('child_process');

const argv = process.argv.slice(2);
const generatedOnly = argv.includes('--generated-only');

const datasets = (() => {
  const i = argv.indexOf('--dataset');
  if (i !== -1 && argv[i + 1]) return [argv[i + 1]];
  // All first-class datasets. Thunderspy is now regenerated by default (its
  // generated/ tree reproduces byte-identical from committed exported_powers/,
  // same as HC/Rebirth) so the regen-diff CI guard covers it too — closing the
  // "converter fix regenerated some datasets, not others" staleness class
  // (the DSH8 Clarion leak).
  return ['homecoming', 'rebirth', 'thunderspy'];
})();

// Steps in dependency order. The two that write under generated/ vs the layered
// powersets/ tree are tagged so --generated-only can skip the downstream ones.
// NB convert-pool-powers / convert-epic-pools DRY-RUN unless given --apply, so
// they must carry it here or the orchestrator silently never refreshes
// generated/power-pools.ts + epic-pools.ts (and CI's regen-diff misses pool/epic
// drift entirely).
//   convert-all-powersets  -> generated/powersets/** (+ composed powersets/**)
//   convert-pool-powers    -> generated/power-pools.ts
//   convert-epic-pools     -> generated/epic-pools.ts
//   convert-incarnate      -> generated/incarnate-effects.ts
//   convert-salvage        -> generated/invention-salvage.generated.ts (salvage.bin)
//   extract-at-tables      -> at-tables.ts            (layered, not generated/)
//   convert-archetypes     -> generated/archetype-stats.generated.ts (HP/cap/resCap)
//   generate-powerset-index-> powersets/index.ts      (needs powersets first)
//   generate-kheldian      -> kheldian-form-variants.ts
//   convert-pet-entities   -> pet-entities.ts (+ sidecars)
const STEPS = [
  { script: 'extract-at-tables.cjs',          args: [],          generated: false },
  { script: 'convert-archetypes.cjs',         args: [],          generated: true },
  { script: 'convert-all-powersets.cjs',      args: ['--force'], generated: true },
  { script: 'generate-powerset-index.cjs',    args: [],          generated: false },
  { script: 'generate-kheldian-variants.cjs', args: [],          generated: false },
  { script: 'convert-pool-powers.cjs',        args: ['--apply'], generated: true },
  { script: 'convert-epic-pools.cjs',         args: ['--apply'], generated: true },
  { script: 'convert-incarnate-effects.cjs',  args: [],          generated: true },
  { script: 'convert-salvage.cjs',            args: [],          generated: true },
  { script: 'convert-pet-entities.cjs',       args: [],          generated: false },
  // Guard: fail the regen if a malformed boostset poisoned a whole IO-set
  // category (the Thunderspy "KB"/SumoBoostName pollution class). Runs on the
  // freshly-generated output, so it also gates the CI regen-and-diff pass.
  { script: 'audit-allowed-set-categories.cjs', args: ['--gate'], generated: true },
];

const steps = generatedOnly ? STEPS.filter((s) => s.generated) : STEPS;

const started = process.hrtime.bigint();
for (const ds of datasets) {
  console.log(`\n========== REGEN dataset: ${ds}${generatedOnly ? ' (generated-only)' : ''} ==========`);
  for (const { script, args } of steps) {
    const cmd = `node scripts/${script} --dataset ${ds} ${args.join(' ')}`.trim();
    console.log(`\n>>> ${cmd}`);
    execSync(cmd, { stdio: 'inherit' });
  }
}

// DSH6 completeness gate (Phase 0b) — runs ONCE after the dataset loop (the
// detector sweeps the HC generated tree only). Fails the regen if any collapse
// or whole-class-absent group is missing from the frozen allowlist
// (scripts/dsh6-gate-allowlist.json) — the PotD-class silent drop now fails
// here instead of hiding in a non-gating bucket. Side effect: the detector
// rewrites dsh6-collapse-worklist.json, so the CI regen-diff also catches a
// stale committed worklist. Skipped for a single non-HC --dataset run (the
// HC generated tree it checks wasn't touched).
if (datasets.includes('homecoming')) {
  const cmd = 'node scripts/dsh6-collapse-detector.cjs --gate';
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// Plan B Phase-1 shadow compare — every discriminator the PowerEffects bag
// carries (the `*Unenhanced` slots, `unresistable`, `toWho:'Self'`,
// `durationVariants`) must be recoverable from the power's atom list. This is
// the precondition for Phase 2 migrating each calc applier off the bag: an
// atom list missing a bag fact would drop it silently. Sweeps every dataset
// just regenerated (~4s), so it also catches an atom-emit regression the
// regen-diff byte gate would see only as churn.
{
  const cmd = `node scripts/planb-shadow-bag.cjs ${datasets.map((d) => `--dataset ${d}`).join(' ')}`;
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}
const secs = Number(process.hrtime.bigint() - started) / 1e9;
console.log(`\n=== regen complete in ${secs.toFixed(0)}s ===`);
