/**
 * Auto-generated piece-name aliases: maps (setId, Mids piece name) to piece
 * number in our data. Built by comparing HC parser display names to our
 * io-sets-raw.ts piece names. Source: scripts/build-legacy-piece-aliases.py.
 *
 * Hand-curated additions appear at the end, keyed on Mids display names that
 * the normalization/aspect-match paths can't disambiguate.
 */
export const LEGACY_PIECE_ALIASES: Record<string, number> = {
  // --- Hand-curated (confirmed by user guidance, docs/mids-unresolved-pieces.md) ---

  // Commanding Presence: Mids "Threat/Placate Resist" → our piece 5 "+Resist Threat".
  "commanding_presence\u0000threat/placate resist": 5,

  // Taunt sets — Mids lists Placate as an aspect we don't carry; pieces map to
  // their aspect-count counterparts in our data.
  "mocking_beratement\u0000threat/placate": 1,
  "mocking_beratement\u0000threat/placate/recharge/range": 3,
  "perfect_zinger\u0000threat/placate": 1,
  "perfect_zinger\u0000threat/placate/recharge/range": 3,

  // Kinetic Combat "Knockdown Bonus" → our piece 5 "Chance for Knockback".
  "kinetic_combat\u0000knockdown bonus": 5,

  // Gladiator's Armor aspect-order swaps.
  "gladiators_armor\u0000end/resist": 1,
  "gladiators_armor\u0000recharge/resist": 2,

  // Synapse's Shock "Increased Run Speed" → our piece 6 "EndMod/+Run Speed".
  "synapses_shock\u0000endmod/increased run speed": 6,

  // Superior Kheldian's Grace "Form Empowerment" → our piece 6 (ATO proc piece).
  "superior_kheldians_grace\u0000recharge/form empowerment": 6,

  // Arsenal Control ATO T6 proc pieces — our piece 6 names start with "Chance for X"
  // which our aspect parser treats as proc-like, so explicit aliases are needed.
  "superior_overpowering_presence\u0000rechargetime/energy font": 6,
  "overpowering_presence\u0000rechargetime/energy font": 6,
  "superior_dominating_grasp\u0000rechargetime/fiery orb": 6,
  "dominating_grasp\u0000rechargetime/fiery orb": 6,

  // Travel sets — Mids names with "Increased X" resistance/height/protection
  // → our piece 4 (the unique buff piece).
  "thrust\u0000running / increased run speed resistance": 4,
  "launch\u0000jumping / increased jump height": 4,
  "hypersonic\u0000flying / increased fly protection": 4,
  "warp\u0000range / increased perception": 4,

  // --- Auto-generated (328 entries) ---

  "absolute_amazement\u0000stun duration": 1,
  "absolute_amazement\u0000stun duration/recharge": 2,
  "absolute_amazement\u0000stun duration/recharge/accuracy": 3,
  "absolute_amazement\u0000recharge/accuracy": 4,
  "absolute_amazement\u0000stun duration/endurance reduction": 5,
  "absolute_amazement\u0000chance for to hit debuff": 6,
  "achilles_heel\u0000chance for resistance debuff": 3,
  "adjusted_targeting\u0000to hit buff": 1,
  "adjusted_targeting\u0000to hit buff/recharge": 2,
  "adjusted_targeting\u0000to hit buff/recharge/endurance reduction": 3,
  "adjusted_targeting\u0000recharge/endurance reduction": 4,
  "adjusted_targeting\u0000to hit buff/endurance reduction": 5,
  "adrenal_adjustment\u0000endurance modification": 1,
  "adrenal_adjustment\u0000endurance modification/recharge": 2,
  "adrenal_adjustment\u0000endurance modification/recharge/accuracy": 3,
  "aegis\u0000resistance/endurance": 1,
  "aegis\u0000resistance/recharge": 2,
  "aegis\u0000resistance/endurance/recharge": 4,
  "aegis\u0000resistance": 5,
  "aegis\u0000psionic/status resistance": 6,
  "analyze_weakness\u0000chance for +to hit": 6,
  "annihilation\u0000accuracy/damage/recharge/endurance": 5,
  "annihilation\u0000chance for -res": 6,
  "apocalypse\u0000damage/recharge/accuracy": 3,
  "apocalypse\u0000recharge/accuracy": 4,
  "apocalypse\u0000damage/endurance reduction": 5,
  "armageddon\u0000damage/recharge/accuracy": 3,
  "armageddon\u0000recharge/accuracy": 4,
  "armageddon\u0000damage/endurance reduction": 5,
  "artillery\u0000accuracy/recharge/range": 5,
  "artillery\u0000endurance/recharge/range": 6,
  "basilisks_gaze\u0000recharge/hold": 3,
  "basilisks_gaze\u0000endurance reduction/recharge/hold": 4,
  "basilisks_gaze\u0000accuracy/endurance reduction/recharge/hold": 5,
  "basilisks_gaze\u0000chance for recharge slow": 6,
  "befuddling_aura\u0000endurance/confuse": 2,
  "blessing_of_the_zephyr\u0000run speed, jump, flight speed, range": 1,
  "blessing_of_the_zephyr\u0000run speed, jump, flight speed, range/endurance": 2,
  "blessing_of_the_zephyr\u0000knockback reduction (4 points)": 3,
  "cacophany\u0000endurance/confuse": 2,
  "calibrated_accuracy\u0000accuracy/interrupt": 3,
  "call_of_the_sandman\u0000sleep/range": 4,
  "call_of_the_sandman\u0000accuracy/sleep/recharge": 5,
  "call_of_the_sandman\u0000chance to heal self": 6,
  "call_to_arms\u0000endurance/damage/recharge": 5,
  "call_to_arms\u0000defense bonus aura for pets": 6,
  "celerity\u0000stealth": 3,
  "cloud_senses\u0000to hit debuff": 1,
  "cloud_senses\u0000accuracy/to hit debuff": 2,
  "cloud_senses\u0000to hit debuff/endurance/recharge": 4,
  "coercive_persuasion\u0000confuse duration": 1,
  "coercive_persuasion\u0000confuse duration/recharge": 2,
  "coercive_persuasion\u0000confuse duration/recharge/accuracy": 3,
  "coercive_persuasion\u0000recharge/accuracy": 4,
  "coercive_persuasion\u0000confuse duration/endurance reduction": 5,
  "commanding_presence\u0000taunt/placate resist": 5,
  "dampened_spirits\u0000to hit debuff": 1,
  "dampened_spirits\u0000to hit debuff/recharge": 2,
  "dampened_spirits\u0000to hit debuff/recharge/endurance reduction": 3,
  "dampened_spirits\u0000recharge/endurance reduction": 4,
  "dampened_spirits\u0000to hit debuff/endurance reduction": 5,
  "dark_watchers_despair\u0000to hit debuff": 1,
  "dark_watchers_despair\u0000to hit debuff/recharge": 2,
  "dark_watchers_despair\u0000to hit debuff/recharge/endurance reduction": 3,
  "dark_watchers_despair\u0000recharge/endurance reduction": 4,
  "dark_watchers_despair\u0000to hit debuff/endurance reduction": 5,
  "dark_watchers_despair\u0000chance for recharge slow": 6,
  "debiliative_action\u0000immobilize/endurance reduction": 2,
  "debiliative_action\u0000accuracy/immob/recharge": 5,
  "debiliative_action\u0000disorient bonus": 6,
  "deflated_ego\u0000to hit debuff": 1,
  "deflated_ego\u0000to hit debuff/recharge": 2,
  "deflated_ego\u0000chance for recovery debuff": 3,
  "discouraging_words\u0000to hit debuff": 1,
  "discouraging_words\u0000to hit debuff/recharge": 2,
  "discouraging_words\u0000to hit debuff/recharge/endurance reduction": 3,
  "doctored_wounds\u0000healing/absorb/endurance": 1,
  "doctored_wounds\u0000healing/absorb/recharge": 3,
  "doctored_wounds\u0000healing/absorb/endurance/recharge": 4,
  "doctored_wounds\u0000healing/absorb": 5,
  "edict_of_the_master\u0000defense bonus": 6,
  "efficacy_adaptor\u0000endurance modification": 1,
  "efficacy_adaptor\u0000endurance modification/recharge": 2,
  "efficacy_adaptor\u0000endurance modification/recharge/accuracy": 3,
  "efficacy_adaptor\u0000recharge/accuracy": 4,
  "efficacy_adaptor\u0000endurance modification/accuracy": 5,
  "efficacy_adaptor\u0000endurance modification/endurance reduction": 6,
  "encouraged_accuracy\u0000to hit buff": 1,
  "encouraged_accuracy\u0000to hit buff/recharge": 2,
  "encouraged_accuracy\u0000to hit buff/recharge/endurance reduction": 3,
  "energy_manipulator\u0000endurance modification": 1,
  "energy_manipulator\u0000endurance modification/recharge": 2,
  "energy_manipulator\u0000chance to stun": 3,
  "enfeebled_operation\u0000accuracy/immob/recharge": 5,
  "entropic_chaos\u0000chance to heal self": 5,
  "executioners_contract\u0000damage/interrupt": 3,
  "executioners_contract\u0000disorient bonus": 6,
  "expedient_reinforcement\u0000endurance/damage/recharge": 5,
  "expedient_reinforcement\u0000resist bonus aura for pets": 6,
  "experienced_marksman\u0000damage/endurance/interrupt": 3,
  "experienced_marksman\u0000damage/interrupt/range/recharge": 5,
  "exploited_vulnerability\u0000defense debuff/recharge/endurance reduction": 3,
  "explosive_strike\u0000knockback/damage": 1,
  "explosive_strike\u0000knockback/accuracy": 2,
  "extreme_measures\u0000accuracy/interrupt/range": 3,
  "extreme_measures\u0000damage/interrupt/recharge": 4,
  "force_feedback\u0000knockback/damage": 1,
  "force_feedback\u0000knockback/accuracy": 2,
  "force_feedback\u0000recharge/endurance": 4,
  "force_feedback\u0000knockback/damage/endurance": 5,
  "fortunata_hypnosis\u0000sleep duration": 1,
  "fortunata_hypnosis\u0000sleep duration/recharge": 2,
  "fortunata_hypnosis\u0000sleep duration/recharge/accuracy": 3,
  "fortunata_hypnosis\u0000recharge/accuracy": 4,
  "fortunata_hypnosis\u0000sleep duration/endurance reduction": 5,
  "freebird\u0000stealth": 3,
  "fury_of_the_gladiator\u0000damage/accuracy": 1,
  "fury_of_the_gladiator\u0000chance for -res": 6,
  "gaussians_synchronized_firecontrol\u0000to hit buff": 1,
  "gaussians_synchronized_firecontrol\u0000to hit buff/recharge": 2,
  "gaussians_synchronized_firecontrol\u0000to hit buff/recharge/endurance reduction": 3,
  "gaussians_synchronized_firecontrol\u0000recharge/endurance reduction": 4,
  "gaussians_synchronized_firecontrol\u0000to hit buff/endurance reduction": 5,
  "gift_of_the_ancients\u0000defense/increased run speed": 6,
  "gladiators_armor\u0000resistance/endurance": 1,
  "gladiators_armor\u0000resistance/recharge": 2,
  "gladiators_armor\u0000resistance/endurance/recharge": 4,
  "gladiators_armor\u0000resistance": 5,
  "gladiators_armor\u0000teleportation protection, +def(all)": 6,
  "gladiators_javelin\u0000damage/accuracy": 1,
  "gladiators_net\u0000recharge/hold": 3,
  "gladiators_net\u0000endurance reduction/recharge/hold": 4,
  "gladiators_net\u0000accuracy/endurance reduction/recharge/hold": 5,
  "gladiators_strike\u0000damage/accuracy": 1,
  "glimpse_of_the_abyss\u0000endurance/fear": 2,
  "glimpse_of_the_abyss\u0000fear/range": 4,
  "glimpse_of_the_abyss\u0000accuracy/fear/recharge": 5,
  "gravitational_anchor\u0000immobilize duration": 1,
  "gravitational_anchor\u0000immobilize duration/recharge": 2,
  "gravitational_anchor\u0000immobilize duration/recharge/accuracy": 3,
  "gravitational_anchor\u0000recharge/accuracy": 4,
  "gravitational_anchor\u0000immobilize duration/endurance reduction": 5,
  "harmonized_healing\u0000healing/absorb/endurance": 1,
  "harmonized_healing\u0000healing/absorb/recharge": 3,
  "harmonized_healing\u0000healing/absorb/endurance/recharge": 4,
  "harmonized_healing\u0000healing/absorb": 5,
  "hecatomb\u0000damage/recharge/accuracy": 3,
  "hecatomb\u0000recharge/accuracy": 4,
  "hecatomb\u0000damage/endurance reduction": 5,
  "hibernation\u0000sleep/range": 4,
  "hibernation\u0000accuracy/sleep/recharge": 5,
  "horror\u0000endurance/fear": 2,
  "horror\u0000fear/range": 4,
  "horror\u0000accuracy/fear/recharge": 5,
  "hypersonic\u0000flying speed": 1,
  "hypersonic\u0000flying speed/endurance": 2,
  "ice_mistrals_torment\u0000slow/endurance": 1,
  "impervious_skin\u0000resistance/endurance": 1,
  "impervious_skin\u0000resistance/recharge": 2,
  "impervious_skin\u0000resistance/endurance/recharge": 4,
  "impervious_skin\u0000status resistance/regeneration": 5,
  "impervium_armor\u0000resistance/endurance": 1,
  "impervium_armor\u0000resistance/recharge": 2,
  "impervium_armor\u0000resistance/endurance/recharge": 4,
  "impervium_armor\u0000resistance": 5,
  "impervium_armor\u0000psionic resistance": 6,
  "induced_coma\u0000sleep/range": 4,
  "induced_coma\u0000accuracy/sleep/recharge": 5,
  "induced_coma\u0000chance for recharge slow": 6,
  "javelin_volley\u0000damage/accuracy": 1,
  "kinetic_combat\u0000chance for knockdown": 5,
  "kinetic_crash\u0000knockback/damage": 1,
  "kinetic_crash\u0000knockback/accuracy": 2,
  "kinetic_crash\u0000recharge/endurance": 4,
  "kinetic_crash\u0000knockback/damage/endurance": 5,
  "kinetic_crash\u0000knockback/damage/accuracy": 6,
  "launch\u0000jumping speed": 1,
  "launch\u0000jumping speed/endurance": 2,
  "launch\u0000jumping speed/increased jump height": 4,
  "lethargic_repose\u0000sleep/range": 4,
  "lethargic_repose\u0000accuracy/sleep/recharge": 5,
  "lockdown\u0000recharge/hold": 3,
  "lockdown\u0000endurance reduction/recharge/hold": 4,
  "lockdown\u0000accuracy/endurance reduction/recharge/hold": 5,
  "lockdown\u0000chance for +2 mag hold": 6,
  "luck_of_the_gambler\u0000defense/increased global recharge speed": 6,
  "malaises_illusions\u0000endurance/confuse": 2,
  "miracle\u0000healing/absorb/endurance": 1,
  "miracle\u0000healing/absorb/recharge": 3,
  "miracle\u0000healing/absorb/endurance/recharge": 4,
  "miracle\u0000healing/absorb": 5,
  "mocking_beratement\u0000recharge/accuracy": 4,
  "nightmare\u0000endurance/fear": 2,
  "nightmare\u0000fear/range": 4,
  "nightmare\u0000accuracy/fear/recharge": 5,
  "nightmare\u0000accuracy/fear": 6,
  "numinas_convalesence\u0000healing/absorb/endurance": 1,
  "numinas_convalesence\u0000healing/absorb/recharge": 3,
  "numinas_convalesence\u0000healing/absorb/endurance/recharge": 4,
  "numinas_convalesence\u0000healing/absorb": 5,
  "numinas_convalesence\u0000regeneration/recovery": 6,
  "pacing_of_the_turtle\u0000chance for recharge slow": 6,
  "panacea\u0000healing/absorb/endurance": 1,
  "panacea\u0000healing/absorb/recharge": 3,
  "panacea\u0000healing/absorb/endurance/recharge": 4,
  "panacea\u0000healing/absorb": 5,
  "panacea\u0000chance for +hit points/endurance": 6,
  "perfect_zinger\u0000recharge/accuracy": 4,
  "performance_shifter\u0000endurance modification": 1,
  "performance_shifter\u0000endurance modification/recharge": 2,
  "performance_shifter\u0000endurance modification/recharge/accuracy": 3,
  "performance_shifter\u0000recharge/accuracy": 4,
  "performance_shifter\u0000endurance modification/accuracy": 5,
  "perplex\u0000endurance/confuse": 2,
  "perplex\u0000recharge/confuse": 6,
  "pounding_slugfest\u0000disorient bonus": 4,
  "power_transfer\u0000endurance modification": 1,
  "power_transfer\u0000damage/endurance modification": 3,
  "power_transfer\u0000accuracy/damage/recharge/endurance": 5,
  "power_transfer\u0000chance to heal self": 6,
  "preemptive_optimization\u0000endurance modification/endurance reduction": 2,
  "preemptive_optimization\u0000endurance modification/recharge": 3,
  "preemptive_optimization\u0000endurance modification/accuracy/endurance": 4,
  "preemptive_optimization\u0000endurance modification/accuracy/recharge": 5,
  "preemptive_optimization\u0000endurance modification/endurance/recharge": 6,
  "preventive_medicine\u0000healing/absorb": 1,
  "preventive_medicine\u0000healing/absorb/endurance": 2,
  "preventive_medicine\u0000recharge/endurance": 3,
  "preventive_medicine\u0000healing/absorb/recharge": 4,
  "preventive_medicine\u0000healing/absorb/endurance/recharge": 5,
  "preventive_medicine\u0000absorb proc": 6,
  "ragnarok\u0000damage/recharge/accuracy": 3,
  "ragnarok\u0000recharge/accuracy": 4,
  "ragnarok\u0000damage/endurance reduction": 5,
  "ragnarok\u0000chance for knockdown": 6,
  "razzle_dazzle\u0000stun/range": 4,
  "razzle_dazzle\u0000accuracy/stun/recharge": 5,
  "reactive_armor\u0000resistance/endurance": 1,
  "reactive_armor\u0000resistance/recharge": 2,
  "reactive_armor\u0000resistance/endurance/recharge": 4,
  "reactive_armor\u0000resistance": 5,
  "reactive_defenses\u0000scaling damage resistance": 6,
  "rectified_reticle\u0000to hit buff": 1,
  "rectified_reticle\u0000to hit buff/recharge": 2,
  "rectified_reticle\u0000increased perception": 3,
  "regenerative_tissue\u0000healing/absorb/endurance": 1,
  "regenerative_tissue\u0000healing/absorb/recharge": 3,
  "regenerative_tissue\u0000healing/absorb/endurance/recharge": 4,
  "regenerative_tissue\u0000regeneration": 5,
  "rooting_grasp\u0000accuracy/immob/recharge": 5,
  "rope_a_dope\u0000stun/range": 4,
  "rope_a_dope\u0000accuracy/stun/recharge": 5,
  "shield_wall\u0000teleportation protection, +res(all)": 6,
  "siphon_insight\u0000to hit debuff": 1,
  "siphon_insight\u0000accuracy/to hit debuff": 2,
  "siphon_insight\u0000to hit debuff/endurance/recharge": 4,
  "siphon_insight\u0000chance for +to hit": 6,
  "soulbound_allegiance\u0000damage/recharge/accuracy": 3,
  "soulbound_allegiance\u0000recharge/accuracy": 4,
  "soulbound_allegiance\u0000damage/endurance reduction": 5,
  "sovereign_right\u0000resistance bonus": 6,
  "stagger\u0000stun/range": 4,
  "stagger\u0000accuracy/stun/recharge": 5,
  "steadfast_protection\u0000resistance/endurance": 1,
  "steadfast_protection\u0000resistance/defense": 2,
  "sting_of_the_manticore\u0000accuracy/interrupt/range": 3,
  "sting_of_the_manticore\u0000damage/interrupt/recharge": 4,
  "stupefy\u0000stun/range": 4,
  "stupefy\u0000accuracy/stun/recharge": 5,
  "sudden_acceleration\u0000knockback/accuracy": 1,
  "sudden_acceleration\u0000knockback/recharge": 2,
  "sudden_acceleration\u0000knockback/damage/endurance": 3,
  "sudden_acceleration\u0000knockback/damage/recharge": 4,
  "sudden_acceleration\u0000knockback/accuracy/damage": 5,
  "sudden_acceleration\u0000knockback to knockdown": 6,
  "synapses_shock\u0000endurance modification": 1,
  "synapses_shock\u0000endurance modification/recharge": 3,
  "synapses_shock\u0000endurance modification/increased run speed": 6,
  "tempest\u0000chance for endurance drain": 4,
  "theft_of_essence\u0000healing/absorb": 1,
  "theft_of_essence\u0000healing/absorb/recharge": 2,
  "theft_of_essence\u0000accuracy/healing/absorb": 3,
  "theft_of_essence\u0000accuracy/endurance/healing/absorb": 4,
  "thrust\u0000running speed": 1,
  "thrust\u0000running speed/endurance": 2,
  "titanium_coating\u0000resistance/endurance": 1,
  "titanium_coating\u0000resistance/recharge": 2,
  "titanium_coating\u0000resistance/endurance/recharge": 4,
  "titanium_coating\u0000resistance": 5,
  "touch_of_death\u0000negative energy damage": 6,
  "touch_of_lady_grey\u0000defense debuff/recharge/endurance reduction": 3,
  "touch_of_lady_grey\u0000recharge/endurance reduction": 4,
  "touch_of_lady_grey\u0000defense debuff/endurance reduction": 5,
  "touch_of_the_nictus\u0000healing/absorb": 1,
  "touch_of_the_nictus\u0000healing/absorb/recharge": 2,
  "touch_of_the_nictus\u0000accuracy/healing/absorb": 3,
  "touch_of_the_nictus\u0000accuracy/endurance/healing/absorb": 4,
  "trap_of_the_hunter\u0000immobilize/accuracy": 4,
  "trap_of_the_hunter\u0000accuracy/immob/recharge": 5,
  "triage\u0000healing/absorb/endurance": 1,
  "triage\u0000healing/absorb/recharge": 3,
  "triage\u0000healing/absorb/endurance/recharge": 4,
  "triumphant_insult\u0000chance to disorient": 3,
  "unbounded_leap\u0000stealth": 3,
  "unbreakable_constraint\u0000hold duration": 1,
  "unbreakable_constraint\u0000hold duration/recharge": 2,
  "unbreakable_constraint\u0000hold duration/recharge/accuracy": 3,
  "unbreakable_constraint\u0000recharge/accuracy": 4,
  "unbreakable_constraint\u0000hold duration/endurance reduction": 5,
  "unbreakable_guard\u0000resistance": 1,
  "unbreakable_guard\u0000resistance/endurance": 2,
  "unbreakable_guard\u0000resistance/recharge": 4,
  "unbreakable_guard\u0000resistance/endurance/recharge": 5,
  "unbreakable_guard\u0000+7.5% max hp": 6,
  "undermined_defenses\u0000defense debuff/recharge/endurance reduction": 3,
  "undermined_defenses\u0000recharge/endurance reduction": 4,
  "undermined_defenses\u0000defense debuff/endurance reduction": 5,
  "unspeakable_terror\u0000endurance/fear": 2,
  "unspeakable_terror\u0000fear/range": 4,
  "unspeakable_terror\u0000accuracy/fear/recharge": 5,
  "unspeakable_terror\u0000disorient bonus": 6,
  "volley_of_velocity\u0000knockback/damage": 1,
  "volley_of_velocity\u0000knockback/accuracy": 2,
  "warp\u0000range/endurance": 2,
  "warp\u0000range/increased perception": 4,
  "winters_gift\u0000run speed, jump, flight speed, range": 1,
  "winters_gift\u0000run speed, jump, flight speed, range/endurance": 2,
  "winters_gift\u0000slow resistance (20%)": 3,
};
