/**
 * Incarnate Effects — Auto-generated from raw Homecoming server data
 *
 * Generated by: scripts/convert-incarnate-effects.cjs
 * Source: raw_data_homecoming-20251209_7415/powers/incarnate/
 *
 * DO NOT EDIT MANUALLY — re-run the script to regenerate.
 */

// ============================================
// ALPHA EFFECTS
// ============================================

export interface AlphaEffects {
  /** Enhancement bonuses (decimal, e.g. 0.33 = 33%). Keys are enhancement aspect names. */
  [aspect: string]: number | undefined;
  levelShift?: number;
}

const ALPHA_EFFECTS: Record<string, AlphaEffects> = {
  // Agility Boost
  'agility_boost': {
    enduranceModification: 0.275,
  },
  // Agility Core Boost
  'agility_core_boost': {
    enduranceModification: 0.22,
    recharge: 0.22,
  },
  // Agility Core Paragon
  'agility_core_paragon': {
    levelShift: 1,
    enduranceModification: 0.15,
    recharge: 0.11,
    defense: 0.0667,
  },
  // Agility Partial Core Revamp
  'agility_partial_core_revamp': {
    levelShift: 1,
    enduranceModification: 0.165,
    recharge: 0.165,
    defense: 0.1,
  },
  // Agility Partial Radial Revamp
  'agility_partial_radial_revamp': {
    levelShift: 1,
    enduranceModification: 0.165,
    recharge: 0.0825,
    defense: 0.1,
    runSpeed: 0.165,
  },
  // Agility Radial Boost
  'agility_radial_boost': {
    enduranceModification: 0.22,
    defense: 0.1333,
  },
  // Agility Radial Paragon
  'agility_radial_paragon': {
    levelShift: 1,
    enduranceModification: 0.11,
    recharge: 0.11,
    defense: 0.0667,
    jumpSpeed: 0.11,
    runSpeed: 0.11,
    flySpeed: 0.11,
  },
  // Agility Total Core Revamp
  'agility_total_core_revamp': {
    levelShift: 1,
    enduranceModification: 0.225,
    recharge: 0.165,
  },
  // Agility Total Radial Revamp
  'agility_total_radial_revamp': {
    levelShift: 1,
    enduranceModification: 0.165,
    recharge: 0.0825,
    defense: 0.1,
    jumpSpeed: 0.165,
  },
  // Cardiac Boost
  'cardiac_boost': {
    enduranceReduction: 0.275,
  },
  // Cardiac Core Boost
  'cardiac_core_boost': {
    enduranceReduction: 0.22,
    range: 0.1333,
  },
  // Cardiac Core Paragon
  'cardiac_core_paragon': {
    levelShift: 1,
    enduranceReduction: 0.15,
    range: 0.0667,
    resistance: 0.0667,
  },
  // Cardiac Partial Core Revamp
  'cardiac_partial_core_revamp': {
    levelShift: 1,
    enduranceReduction: 0.165,
    range: 0.1,
    resistance: 0.1,
  },
  // Cardiac Partial Radial Revamp
  'cardiac_partial_radial_revamp': {
    levelShift: 1,
    enduranceReduction: 0.165,
    range: 0.05,
    resistance: 0.1,
    fear: 0.165,
  },
  // Cardiac Radial Boost
  'cardiac_radial_boost': {
    enduranceReduction: 0.22,
    resistance: 0.1333,
  },
  // Cardiac Radial Paragon
  'cardiac_radial_paragon': {
    levelShift: 1,
    enduranceReduction: 0.11,
    range: 0.0667,
    resistance: 0.0667,
    sleep: 0.11,
    fear: 0.11,
    intangible: 0.11,
  },
  // Cardiac Total Core Revamp
  'cardiac_total_core_revamp': {
    levelShift: 1,
    enduranceReduction: 0.225,
    range: 0.1,
  },
  // Cardiac Total Radial Revamp
  'cardiac_total_radial_revamp': {
    levelShift: 1,
    enduranceReduction: 0.165,
    range: 0.05,
    resistance: 0.1,
    sleep: 0.165,
  },
  // Intuition Boost
  'intuition_boost': {
    hold: 0.275,
  },
  // Intuition Core Boost
  'intuition_core_boost': {
    hold: 0.22,
    defenseDebuff: 0.22,
  },
  // Intuition Core Paragon
  'intuition_core_paragon': {
    levelShift: 1,
    hold: 0.15,
    defenseDebuff: 0.11,
    range: 0.0667,
  },
  // Intuition Partial Core Revamp
  'intuition_partial_core_revamp': {
    levelShift: 1,
    hold: 0.165,
    defenseDebuff: 0.165,
    range: 0.1,
  },
  // Intuition Partial Radial Revamp
  'intuition_partial_radial_revamp': {
    levelShift: 1,
    hold: 0.165,
    defenseDebuff: 0.0825,
    range: 0.1,
    damage: 0.165,
  },
  // Intuition Radial Boost
  'intuition_radial_boost': {
    hold: 0.22,
    range: 0.1333,
  },
  // Intuition Radial Paragon
  'intuition_radial_paragon': {
    levelShift: 1,
    hold: 0.11,
    defenseDebuff: 0.11,
    range: 0.0667,
    toHitDebuff: 0.0667,
    damage: 0.11,
    slow: 0.11,
  },
  // Intuition Total Core Revamp
  'intuition_total_core_revamp': {
    levelShift: 1,
    hold: 0.225,
    defenseDebuff: 0.165,
  },
  // Intuition Total Radial Revamp
  'intuition_total_radial_revamp': {
    levelShift: 1,
    hold: 0.165,
    defenseDebuff: 0.0825,
    range: 0.1,
    toHitDebuff: 0.1,
  },
  // Musculature Boost
  'musculature_boost': {
    damage: 0.275,
  },
  // Musculature Core Boost
  'musculature_core_boost': {
    damage: 0.22,
    immobilize: 0.22,
  },
  // Musculature Core Paragon
  'musculature_core_paragon': {
    levelShift: 1,
    damage: 0.15,
    immobilize: 0.11,
    defenseDebuff: 0.11,
  },
  // Musculature Partial Core Revamp
  'musculature_partial_core_revamp': {
    levelShift: 1,
    damage: 0.165,
    immobilize: 0.165,
    defenseDebuff: 0.165,
  },
  // Musculature Partial Radial Revamp
  'musculature_partial_radial_revamp': {
    levelShift: 1,
    damage: 0.165,
    immobilize: 0.0825,
    defenseDebuff: 0.165,
    toHitDebuff: 0.1,
  },
  // Musculature Radial Boost
  'musculature_radial_boost': {
    damage: 0.22,
    defenseDebuff: 0.22,
  },
  // Musculature Radial Paragon
  'musculature_radial_paragon': {
    levelShift: 1,
    damage: 0.11,
    immobilize: 0.11,
    defenseDebuff: 0.11,
    enduranceModification: 0.11,
    toHitDebuff: 0.0667,
    runSpeed: 0.11,
  },
  // Musculature Total Core Revamp
  'musculature_total_core_revamp': {
    levelShift: 1,
    damage: 0.225,
    immobilize: 0.165,
  },
  // Musculature Total Radial Revamp
  'musculature_total_radial_revamp': {
    levelShift: 1,
    damage: 0.165,
    immobilize: 0.0825,
    defenseDebuff: 0.165,
    enduranceModification: 0.165,
  },
  // Nerve Boost
  'nerve_boost': {
    accuracy: 0.275,
  },
  // Nerve Core Boost
  'nerve_core_boost': {
    accuracy: 0.22,
    hold: 0.22,
  },
  // Nerve Core Paragon
  'nerve_core_paragon': {
    levelShift: 1,
    accuracy: 0.15,
    hold: 0.11,
    defense: 0.0667,
  },
  // Nerve Partial Core Revamp
  'nerve_partial_core_revamp': {
    levelShift: 1,
    accuracy: 0.165,
    hold: 0.165,
    defense: 0.1,
  },
  // Nerve Partial Radial Revamp
  'nerve_partial_radial_revamp': {
    levelShift: 1,
    accuracy: 0.165,
    hold: 0.0825,
    defense: 0.1,
    taunt: 0.165,
  },
  // Nerve Radial Boost
  'nerve_radial_boost': {
    accuracy: 0.22,
    defense: 0.1333,
  },
  // Nerve Radial Paragon
  'nerve_radial_paragon': {
    levelShift: 1,
    accuracy: 0.11,
    hold: 0.11,
    defense: 0.0667,
    confuse: 0.11,
    taunt: 0.11,
    flySpeed: 0.11,
  },
  // Nerve Total Core Revamp
  'nerve_total_core_revamp': {
    levelShift: 1,
    accuracy: 0.225,
    hold: 0.165,
  },
  // Nerve Total Radial Revamp
  'nerve_total_radial_revamp': {
    levelShift: 1,
    accuracy: 0.165,
    hold: 0.0825,
    defense: 0.1,
    confuse: 0.165,
  },
  // Resilient Boost
  'resilient_boost': {
    resistance: 0.1667,
  },
  // Resilient Core Boost
  'resilient_core_boost': {
    resistance: 0.1333,
    toHitBuff: 0.1333,
  },
  // Resilient Core Paragon
  'resilient_core_paragon': {
    levelShift: 1,
    resistance: 0.11,
    toHitBuff: 0.0667,
    immobilize: 0.11,
  },
  // Resilient Partial Core Revamp
  'resilient_partial_core_revamp': {
    levelShift: 1,
    resistance: 0.1,
    toHitBuff: 0.1,
    immobilize: 0.165,
  },
  // Resilient Partial Radial Revamp
  'resilient_partial_radial_revamp': {
    levelShift: 1,
    resistance: 0.1,
    toHitBuff: 0.05,
    immobilize: 0.165,
    stun: 0.165,
  },
  // Resilient Radial Boost
  'resilient_radial_boost': {
    resistance: 0.1333,
    immobilize: 0.22,
  },
  // Resilient Radial Paragon
  'resilient_radial_paragon': {
    levelShift: 1,
    resistance: 0.0667,
    toHitBuff: 0.0667,
    immobilize: 0.11,
    intangible: 0.11,
    stun: 0.11,
    taunt: 0.11,
  },
  // Resilient Total Core Revamp
  'resilient_total_core_revamp': {
    levelShift: 1,
    resistance: 0.165,
    toHitBuff: 0.1,
  },
  // Resilient Total Radial Revamp
  'resilient_total_radial_revamp': {
    levelShift: 1,
    resistance: 0.1,
    toHitBuff: 0.05,
    immobilize: 0.165,
    intangible: 0.165,
  },
  // Spiritual Boost
  'spiritual_boost': {
    recharge: 0.275,
  },
  // Spiritual Core Boost
  'spiritual_core_boost': {
    recharge: 0.22,
    stun: 0.22,
  },
  // Spiritual Core Paragon
  'spiritual_core_paragon': {
    levelShift: 1,
    recharge: 0.15,
    stun: 0.11,
    heal: 0.11,
  },
  // Spiritual Partial Core Revamp
  'spiritual_partial_core_revamp': {
    levelShift: 1,
    recharge: 0.165,
    stun: 0.165,
    heal: 0.165,
  },
  // Spiritual Partial Radial Revamp
  'spiritual_partial_radial_revamp': {
    levelShift: 1,
    recharge: 0.165,
    stun: 0.0825,
    heal: 0.165,
    slow: 0.165,
  },
  // Spiritual Radial Boost
  'spiritual_radial_boost': {
    recharge: 0.22,
    heal: 0.22,
  },
  // Spiritual Radial Paragon
  'spiritual_radial_paragon': {
    levelShift: 1,
    recharge: 0.11,
    stun: 0.11,
    heal: 0.11,
    toHitBuff: 0.0667,
    slow: 0.11,
    jumpSpeed: 0.11,
  },
  // Spiritual Total Core Revamp
  'spiritual_total_core_revamp': {
    levelShift: 1,
    recharge: 0.225,
    stun: 0.165,
  },
  // Spiritual Total Radial Revamp
  'spiritual_total_radial_revamp': {
    levelShift: 1,
    recharge: 0.165,
    stun: 0.0825,
    heal: 0.165,
    toHitBuff: 0.1,
  },
  // Vigor Boost
  'vigor_boost': {
    heal: 0.275,
  },
  // Vigor Core Boost
  'vigor_core_boost': {
    heal: 0.22,
    accuracy: 0.22,
  },
  // Vigor Core Paragon
  'vigor_core_paragon': {
    levelShift: 1,
    heal: 0.15,
    accuracy: 0.11,
    enduranceReduction: 0.11,
  },
  // Vigor Partial Core Revamp
  'vigor_partial_core_revamp': {
    levelShift: 1,
    heal: 0.165,
    accuracy: 0.165,
    enduranceReduction: 0.165,
  },
  // Vigor Partial Radial Revamp
  'vigor_partial_radial_revamp': {
    levelShift: 1,
    heal: 0.165,
    accuracy: 0.0825,
    enduranceReduction: 0.165,
    sleep: 0.165,
  },
  // Vigor Radial Boost
  'vigor_radial_boost': {
    heal: 0.22,
    enduranceReduction: 0.22,
  },
  // Vigor Radial Paragon
  'vigor_radial_paragon': {
    levelShift: 1,
    heal: 0.11,
    accuracy: 0.11,
    enduranceReduction: 0.11,
    confuse: 0.11,
    sleep: 0.11,
    fear: 0.11,
  },
  // Vigor Total Core Revamp
  'vigor_total_core_revamp': {
    levelShift: 1,
    heal: 0.225,
    accuracy: 0.165,
  },
  // Vigor Total Radial Revamp
  'vigor_total_radial_revamp': {
    levelShift: 1,
    heal: 0.165,
    accuracy: 0.0825,
    enduranceReduction: 0.165,
    confuse: 0.165,
  },
};

// ============================================
// DESTINY EFFECTS
// ============================================

export interface DestinyEffects {
  levelShift?: number;
  /** Peak stat bonuses (decimals). These diminish over the 120s duration. */
  [stat: string]: number | undefined;
}

const DESTINY_EFFECTS: Record<string, DestinyEffects> = {
  // Ageless Core Epiphany
  'ageless_core_epiphany': {
    levelShift: 1,
    endurance: 1,
    recharge: 0.4,
    recovery: 5,
  },
  // Ageless Core Invocation
  'ageless_core_invocation': {
    endurance: 0.5,
    recharge: 0.4,
    recovery: 5,
  },
  // Ageless Invocation
  'ageless_invocation': {
    endurance: 0.5,
    recharge: 0.4,
  },
  // Ageless Partial Core Invocation
  'ageless_partial_core_invocation': {
    levelShift: 1,
    endurance: 0.75,
    recharge: 0.4,
    recovery: 5,
  },
  // Ageless Partial Radial Invocation
  'ageless_partial_radial_invocation': {
    levelShift: 1,
    endurance: 0.75,
    recharge: 0.4,
    resistanceAll: 0.5,
  },
  // Ageless Radial Epiphany
  'ageless_radial_epiphany': {
    levelShift: 1,
    endurance: 1,
    recharge: 0.4,
    resistanceAll: 0.5,
  },
  // Ageless Radial Invocation
  'ageless_radial_invocation': {
    endurance: 0.5,
    recharge: 0.4,
    resistanceAll: 0.5,
  },
  // Ageless Total Core Invocation
  'ageless_total_core_invocation': {
    levelShift: 1,
    endurance: 0.75,
    recharge: 0.4,
    recovery: 5,
  },
  // Ageless Total Radial Invocation
  'ageless_total_radial_invocation': {
    levelShift: 1,
    endurance: 0.75,
    recharge: 0.4,
    resistanceAll: 0.5,
  },
  // Barrier Core Epiphany
  'barrier_core_epiphany': {
    levelShift: 1,
    defenseAll: 0.575,
    resistanceAll: 0.575,
  },
  // Barrier Core Invocation
  'barrier_core_invocation': {
    defenseAll: 0.6,
    resistanceAll: 0.6,
  },
  // Barrier Invocation
  'barrier_invocation': {
    defenseAll: 0.6,
    resistanceAll: 0.6,
  },
  // Barrier Partial Core Invocation
  'barrier_partial_core_invocation': {
    levelShift: 1,
    defenseAll: 0.575,
    resistanceAll: 0.575,
  },
  // Barrier Partial Radial Invocation
  'barrier_partial_radial_invocation': {
    levelShift: 1,
    defenseAll: 0.6,
    resistanceAll: 0.6,
  },
  // Barrier Radial Epiphany
  'barrier_radial_epiphany': {
    levelShift: 1,
    defenseAll: 0.6,
    resistanceAll: 0.6,
  },
  // Barrier Radial Invocation
  'barrier_radial_invocation': {
    defenseAll: 0.6,
    resistanceAll: 0.6,
  },
  // Barrier Total Core Invocation
  'barrier_total_core_invocation': {
    levelShift: 1,
    defenseAll: 0.6,
    resistanceAll: 0.6,
  },
  // Barrier Total Radial Invocation
  'barrier_total_radial_invocation': {
    levelShift: 1,
    defenseAll: 0.6,
    resistanceAll: 0.6,
  },
  // Clarion Core Epiphany
  'clarion_core_epiphany': {
    levelShift: 1,
    resistanceAll: 2.1,
  },
  // Clarion Core Invocation
  'clarion_core_invocation': {
    resistanceAll: 2.1,
  },
  // Clarion Invocation
  'clarion_invocation': {
    resistanceAll: 3,
  },
  // Clarion Partial Core Invocation
  'clarion_partial_core_invocation': {
    levelShift: 1,
    resistanceAll: 2.1,
  },
  // Clarion Partial Radial Invocation
  'clarion_partial_radial_invocation': {
    levelShift: 1,
    resistanceAll: 3,
  },
  // Clarion Radial Epiphany
  'clarion_radial_epiphany': {
    levelShift: 1,
    resistanceAll: 3,
  },
  // Clarion Radial Invocation
  'clarion_radial_invocation': {
    resistanceAll: 3,
  },
  // Clarion Total Core Invocation
  'clarion_total_core_invocation': {
    levelShift: 1,
    resistanceAll: 2.1,
  },
  // Clarion Total Radial Invocation
  'clarion_total_radial_invocation': {
    levelShift: 1,
    resistanceAll: 3,
  },
  // Incandescence Core Epiphany
  'incandescence_core_epiphany': {
    levelShift: 1,
    resistanceAll: -0.8,
  },
  // Incandescence Core Invocation
  'incandescence_core_invocation': {
    resistanceAll: -0.5,
  },
  // Incandescence Invocation
  'incandescence_invocation': {
    resistanceAll: -0.3,
  },
  // Incandescence Partial Core Invocation
  'incandescence_partial_core_invocation': {
    levelShift: 1,
    resistanceAll: -0.5,
  },
  // Incandescence Partial Radial Invocation
  'incandescence_partial_radial_invocation': {
    levelShift: 1,
    resistanceAll: -0.5,
  },
  // Incandescence Radial Epiphany
  'incandescence_radial_epiphany': {
    levelShift: 1,
    resistanceAll: -0.6,
  },
  // Incandescence Radial Invocation
  'incandescence_radial_invocation': {
    resistanceAll: -0.4,
  },
  // Incandescence Total Core Invocation
  'incandescence_total_core_invocation': {
    levelShift: 1,
    resistanceAll: -0.7,
  },
  // Incandescence Total Radial Invocation
  'incandescence_total_radial_invocation': {
    levelShift: 1,
    resistanceAll: -0.5,
  },
  // Rebirth Core Epiphany
  'rebirth_core_epiphany': {
    levelShift: 1,
  },
  // Rebirth Core Invocation
  'rebirth_core_invocation': {
  },
  // Rebirth Invocation
  'rebirth_invocation': {
  },
  // Rebirth Partial Core Invocation
  'rebirth_partial_core_invocation': {
    levelShift: 1,
  },
  // Rebirth Partial Radial Invocation
  'rebirth_partial_radial_invocation': {
    levelShift: 1,
    regeneration: 10,
  },
  // Rebirth Radial Epiphany
  'rebirth_radial_epiphany': {
    levelShift: 1,
    regeneration: 10,
  },
  // Rebirth Radial Invocation
  'rebirth_radial_invocation': {
    regeneration: 10,
  },
  // Rebirth Total Core Invocation
  'rebirth_total_core_invocation': {
    levelShift: 1,
  },
  // Rebirth Total Radial Invocation
  'rebirth_total_radial_invocation': {
    levelShift: 1,
    regeneration: 10,
  },
};

// ============================================
// HYBRID EFFECTS
// ============================================

export interface HybridEffects {
  tree: string;
  /** Passive bonuses — always-on just by equipping (stat → decimal) */
  passive: Record<string, number>;
  /** Front-loaded bonuses — active when toggle is on, no enemies required (stat → decimal) */
  frontLoaded: Record<string, number>;
  /** Per-target bonuses — stacks per nearby enemy (stat → decimal per enemy) */
  perTarget: Record<string, number>;
  /** Maximum enemies for per-target stacking */
  maxTargets: number;
  duration: number;
  recharge: number;
}

const HYBRID_EFFECTS: Record<string, HybridEffects> = {
  // Assault Core Embodiment
  'assault_core_embodiment': {
    tree: 'assault',
    passive: {"damage":0.1},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Assault Core Genome
  'assault_core_genome': {
    tree: 'assault',
    passive: {"damage":0.05},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Assault Genome
  'assault_genome': {
    tree: 'assault',
    passive: {"damage":0.025},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Assault Partial Core Graft
  'assault_partial_core_graft': {
    tree: 'assault',
    passive: {"damage":0.075},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Assault Partial Radial Graft
  'assault_partial_radial_graft': {
    tree: 'assault',
    passive: {"damage":0.075},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Assault Radial Embodiment
  'assault_radial_embodiment': {
    tree: 'assault',
    passive: {"damage":0.1},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Assault Radial Genome
  'assault_radial_genome': {
    tree: 'assault',
    passive: {"damage":0.05},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Assault Total Core Graft
  'assault_total_core_graft': {
    tree: 'assault',
    passive: {"damage":0.075},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Assault Total Radial Graft
  'assault_total_radial_graft': {
    tree: 'assault',
    passive: {"damage":0.075},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Control Core Embodiment
  'control_core_embodiment': {
    tree: 'control',
    passive: {"statusResistance":0.4},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Control Core Genome
  'control_core_genome': {
    tree: 'control',
    passive: {"statusResistance":0.2},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Control Genome
  'control_genome': {
    tree: 'control',
    passive: {"statusResistance":0.1},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Control Partial Core Graft
  'control_partial_core_graft': {
    tree: 'control',
    passive: {"statusResistance":0.3},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Control Partial Radial Graft
  'control_partial_radial_graft': {
    tree: 'control',
    passive: {"statusResistance":0.3},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Control Radial Embodiment
  'control_radial_embodiment': {
    tree: 'control',
    passive: {"statusResistance":0.4},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Control Radial Genome
  'control_radial_genome': {
    tree: 'control',
    passive: {"statusResistance":0.2},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Control Total Core Graft
  'control_total_core_graft': {
    tree: 'control',
    passive: {"statusResistance":0.3},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Control Total Radial Graft
  'control_total_radial_graft': {
    tree: 'control',
    passive: {"statusResistance":0.3},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Melee Genome
  'melee_genome_1': {
    tree: 'melee',
    passive: {"regeneration":0.075},
    frontLoaded: {"regeneration":0.0585},
    perTarget: {"regeneration":0.0979},
    maxTargets: 4,
    duration: 120,
    recharge: 120,
  },
  // Melee Core Genome
  'melee_genome_2': {
    tree: 'melee',
    passive: {"regeneration":0.15},
    frontLoaded: {"resSmashing":0.0136,"resLethal":0.0136,"resFire":0.0136,"resCold":0.0136,"resEnergy":0.0136,"resNegative":0.0136,"resPsionic":0.0136,"resToxic":0.0136,"regeneration":0.306},
    perTarget: {"resSmashing":0.0066,"resLethal":0.0066,"resFire":0.0066,"resCold":0.0066,"resEnergy":0.0066,"resNegative":0.0066,"resPsionic":0.0066,"resToxic":0.0066,"regeneration":0.1485},
    maxTargets: 4,
    duration: 120,
    recharge: 120,
  },
  // Melee Radial Genome
  'melee_genome_3': {
    tree: 'melee',
    passive: {"regeneration":0.15},
    frontLoaded: {},
    perTarget: {"defRanged":0.005,"defMelee":0.005,"defAoE":0.005,"defSmashing":0.005,"defLethal":0.005,"defFire":0.005,"defCold":0.005,"defEnergy":0.005,"defNegative":0.005,"defPsionic":0.005,"defToxic":0.005,"regeneration":0.225},
    maxTargets: 4,
    duration: 120,
    recharge: 120,
  },
  // Melee Total Core Graft
  'melee_genome_4': {
    tree: 'melee',
    passive: {"regeneration":0.225},
    frontLoaded: {"resSmashing":0.04,"resLethal":0.04,"resFire":0.04,"resCold":0.04,"resEnergy":0.04,"resNegative":0.04,"resPsionic":0.04,"resToxic":0.04,"regeneration":0.675,"protConfuse":2,"protFear":4,"protHold":2,"protImmobilize":2,"protStun":2,"protSleep":2},
    perTarget: {"resSmashing":0.01,"resLethal":0.01,"resFire":0.01,"resCold":0.01,"resEnergy":0.01,"resNegative":0.01,"resPsionic":0.01,"resToxic":0.01,"regeneration":0.1688},
    maxTargets: 4,
    duration: 120,
    recharge: 120,
  },
  // Melee Partial Core Graft
  'melee_genome_5': {
    tree: 'melee',
    passive: {"regeneration":0.225},
    frontLoaded: {"resSmashing":0.07,"resLethal":0.07,"resFire":0.07,"resCold":0.07,"resEnergy":0.07,"resNegative":0.07,"resPsionic":0.07,"resToxic":0.07,"regeneration":1.1813},
    perTarget: {"resSmashing":0.01,"resLethal":0.01,"resFire":0.01,"resCold":0.01,"resEnergy":0.01,"resNegative":0.01,"resPsionic":0.01,"resToxic":0.01,"regeneration":0.1688},
    maxTargets: 7,
    duration: 120,
    recharge: 120,
  },
  // Melee Partial Radial Graft
  'melee_genome_6': {
    tree: 'melee',
    passive: {"regeneration":0.225},
    frontLoaded: {},
    perTarget: {"defRanged":0.01,"defMelee":0.01,"defAoE":0.01,"defSmashing":0.01,"defLethal":0.01,"defFire":0.01,"defCold":0.01,"defEnergy":0.01,"defNegative":0.01,"defPsionic":0.01,"defToxic":0.01,"regeneration":0.3375},
    maxTargets: 7,
    duration: 120,
    recharge: 120,
  },
  // Melee Total Radial Graft
  'melee_genome_7': {
    tree: 'melee',
    passive: {"regeneration":0.225},
    frontLoaded: {},
    perTarget: {"defRanged":0.01,"defMelee":0.01,"defAoE":0.01,"defSmashing":0.01,"defLethal":0.01,"defFire":0.01,"defCold":0.01,"defEnergy":0.01,"defNegative":0.01,"defPsionic":0.01,"defToxic":0.01,"regeneration":0.3375},
    maxTargets: 4,
    duration: 120,
    recharge: 120,
  },
  // Melee Core Embodiment
  'melee_genome_8': {
    tree: 'melee',
    passive: {"regeneration":0.3},
    frontLoaded: {"resSmashing":0.1608,"resLethal":0.1608,"resFire":0.1608,"resCold":0.1608,"resEnergy":0.1608,"resNegative":0.1608,"resPsionic":0.1608,"resToxic":0.1608,"regeneration":2.412},
    perTarget: {"resSmashing":0.0099,"resLethal":0.0099,"resFire":0.0099,"resCold":0.0099,"resEnergy":0.0099,"resNegative":0.0099,"resPsionic":0.0099,"resToxic":0.0099,"regeneration":0.1485},
    maxTargets: 9,
    duration: 120,
    recharge: 120,
  },
  // Melee Radial Embodiment
  'melee_genome_9': {
    tree: 'melee',
    passive: {"regeneration":0.3},
    frontLoaded: {},
    perTarget: {"defRanged":0.015,"defMelee":0.015,"defAoE":0.015,"defSmashing":0.015,"defLethal":0.015,"defFire":0.015,"defCold":0.015,"defEnergy":0.015,"defNegative":0.015,"defPsionic":0.015,"defToxic":0.015,"regeneration":0.45},
    maxTargets: 9,
    duration: 120,
    recharge: 120,
  },
  // Support Genome
  'support_genome': {
    tree: 'support',
    passive: {},
    frontLoaded: {"defMelee":0.02,"defSmashing":0.02,"defLethal":0.02},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Support Core Genome
  'support_genome_2': {
    tree: 'support',
    passive: {},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Support Radial Genome
  'support_genome_3': {
    tree: 'support',
    passive: {},
    frontLoaded: {"defMelee":0.02,"defAoE":0.02,"defSmashing":0.02,"defLethal":0.02,"defEnergy":0.02,"defNegative":0.02},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Support Total Core Graft
  'support_genome_4': {
    tree: 'support',
    passive: {},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Support Partial Core Graft
  'support_genome_5': {
    tree: 'support',
    passive: {},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Support Partial Radial Graft
  'support_genome_6': {
    tree: 'support',
    passive: {},
    frontLoaded: {"defMelee":0.08,"defAoE":0.08,"defSmashing":0.08,"defLethal":0.08,"defFire":0.08,"defCold":0.08,"defEnergy":0.08,"defNegative":0.08},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Support Total Radial Graft
  'support_genome_7': {
    tree: 'support',
    passive: {},
    frontLoaded: {"defMelee":0.06,"defAoE":0.06,"defSmashing":0.06,"defLethal":0.06,"defFire":0.06,"defCold":0.06,"defEnergy":0.06,"defNegative":0.06},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Support Core Embodiment
  'support_genome_8': {
    tree: 'support',
    passive: {},
    frontLoaded: {},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
  // Support Radial Embodiment
  'support_genome_9': {
    tree: 'support',
    passive: {},
    frontLoaded: {"defRanged":0.08,"defMelee":0.08,"defAoE":0.08,"defSmashing":0.08,"defLethal":0.08,"defFire":0.08,"defCold":0.08,"defEnergy":0.08,"defNegative":0.08,"defPsionic":0.08,"defToxic":0.08},
    perTarget: {},
    maxTargets: 0,
    duration: 120,
    recharge: 120,
  },
};

// ============================================
// INTERFACE EFFECTS
// ============================================

export interface InterfaceProc {
  attrib: string;
  scale: number;
  aspect: string;
  target: string;
  duration: string;
}

export interface InterfaceEffects {
  procs: Array<{ chance: number; ref: string }>;
  procEffects: Array<{ name: string; effects: InterfaceProc[] }>;
}

const INTERFACE_EFFECTS: Record<string, InterfaceEffects> = {
  // Cognitive Core Flawless Interface
  'cognitive_core_flawless_interface': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.2,"ref":"unknown"}],
    procEffects: [],
  },
  // Cognitive Core Interface
  'cognitive_core_interface': {
    procs: [{"chance":0.12,"ref":"unknown"}],
    procEffects: [],
  },
  // Cognitive Interface
  'cognitive_interface': {
    procs: [{"chance":0.08,"ref":"unknown"}],
    procEffects: [],
  },
  // Cognitive Partial Core Conversion
  'cognitive_partial_core_conversion': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.12,"ref":"unknown"}],
    procEffects: [],
  },
  // Cognitive Partial Radial Conversion
  'cognitive_partial_radial_conversion': {
    procs: [{"chance":0.5,"ref":"unknown"},{"chance":0.08,"ref":"unknown"}],
    procEffects: [],
  },
  // Cognitive Radial Flawless Interface
  'cognitive_radial_flawless_interface': {
    procs: [{"chance":0.75,"ref":"unknown"},{"chance":0.1,"ref":"unknown"}],
    procEffects: [],
  },
  // Cognitive Radial Interface
  'cognitive_radial_interface': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.08,"ref":"unknown"}],
    procEffects: [],
  },
  // Cognitive Total Core Conversion
  'cognitive_total_core_conversion': {
    procs: [{"chance":0.16,"ref":"unknown"}],
    procEffects: [],
  },
  // Cognitive Total Radial Conversion
  'cognitive_total_radial_conversion': {
    procs: [{"chance":0.75,"ref":"unknown"},{"chance":0.04,"ref":"unknown"}],
    procEffects: [],
  },
  // Degenerative Core Flawless Interface
  'degenerative_core_flawless_interface': {
    procs: [{"chance":0.75,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [],
  },
  // Degenerative Core Interface
  'degenerative_core_interface': {
    procs: [{"chance":0.5,"ref":"unknown"}],
    procEffects: [],
  },
  // Degenerative Interface
  'degenerative_interface': {
    procs: [{"chance":0.25,"ref":"unknown"}],
    procEffects: [],
  },
  // Degenerative Partial Core Conversion
  'degenerative_partial_core_conversion': {
    procs: [{"chance":0.5,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [],
  },
  // Degenerative Partial Radial Conversion
  'degenerative_partial_radial_conversion': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.5,"ref":"unknown"}],
    procEffects: [],
  },
  // Degenerative Radial Flawless Interface
  'degenerative_radial_flawless_interface': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.75,"ref":"unknown"}],
    procEffects: [],
  },
  // Degenerative Radial Interface
  'degenerative_radial_interface': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [],
  },
  // Degenerative Total Core Conversion
  'degenerative_total_core_conversion': {
    procs: [{"chance":0.75,"ref":"unknown"}],
    procEffects: [],
  },
  // Degenerative Total Radial Conversion
  'degenerative_total_radial_conversion': {
    procs: [{"chance":0.75,"ref":"unknown"}],
    procEffects: [],
  },
  // Diamagnetic Core Flawless Interface
  'diamagnetic_core_flawless_interface': {
    procs: [{"chance":1,"ref":"unknown"},{"chance":0.5,"ref":"unknown"}],
    procEffects: [{"name":"to_hit_debuff","effects":[{"attrib":"ToHit","scale":-0.05,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"regen_debuff","effects":[{"attrib":"Regeneration","scale":-0.1,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Diamagnetic Core Interface
  'diamagnetic_core_interface': {
    procs: [{"chance":0.75,"ref":"unknown"}],
    procEffects: [{"name":"to_hit_debuff","effects":[{"attrib":"ToHit","scale":-0.05,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Diamagnetic Interface
  'diamagnetic_interface': {
    procs: [{"chance":0.5,"ref":"unknown"}],
    procEffects: [{"name":"to_hit_debuff","effects":[{"attrib":"ToHit","scale":-0.05,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Diamagnetic Partial Core Conversion
  'diamagnetic_partial_core_conversion': {
    procs: [{"chance":0.75,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"to_hit_debuff","effects":[{"attrib":"ToHit","scale":-0.05,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"regen_debuff","effects":[{"attrib":"Regeneration","scale":-0.1,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Diamagnetic Partial Radial Conversion
  'diamagnetic_partial_radial_conversion': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.75,"ref":"unknown"}],
    procEffects: [{"name":"to_hit_debuff","effects":[{"attrib":"ToHit","scale":-0.05,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"regen_debuff","effects":[{"attrib":"Regeneration","scale":-0.1,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Diamagnetic Radial Flawless Interface
  'diamagnetic_radial_flawless_interface': {
    procs: [{"chance":0.5,"ref":"unknown"},{"chance":1,"ref":"unknown"}],
    procEffects: [{"name":"to_hit_debuff","effects":[{"attrib":"ToHit","scale":-0.05,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"regen_debuff","effects":[{"attrib":"Regeneration","scale":-0.1,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Diamagnetic Radial Interface
  'diamagnetic_radial_interface': {
    procs: [{"chance":0.5,"ref":"unknown"}],
    procEffects: [{"name":"regen_debuff","effects":[{"attrib":"Regeneration","scale":-0.1,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Diamagnetic Total Core Conversion
  'diamagnetic_total_core_conversion': {
    procs: [{"chance":1,"ref":"unknown"}],
    procEffects: [{"name":"to_hit_debuff","effects":[{"attrib":"ToHit","scale":-0.05,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Diamagnetic Total Radial Conversion
  'diamagnetic_total_radial_conversion': {
    procs: [{"chance":1,"ref":"unknown"}],
    procEffects: [{"name":"regen_debuff","effects":[{"attrib":"Regeneration","scale":-0.1,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Gravitic Core Flawless Interface
  'gravitic_core_flawless_interface': {
    procs: [{"chance":0.75,"ref":"unknown"},{"chance":0.75,"ref":"unknown"},{"chance":0.5,"ref":"unknown"}],
    procEffects: [{"name":"recharge_debuff","effects":[{"attrib":"RechargeTime","scale":-0.1,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"movement_debuff","effects":[{"attrib":"JumpHeight","scale":-0.1,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"},{"attrib":"RunningSpeed","scale":-0.1,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"recovery_debuff","effects":[{"attrib":"Recovery","scale":-0.1,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Gravitic Core Interface
  'gravitic_core_interface': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"recharge_debuff","effects":[{"attrib":"RechargeTime","scale":-0.1,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"movement_debuff","effects":[{"attrib":"JumpHeight","scale":-0.1,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"},{"attrib":"RunningSpeed","scale":-0.1,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Gravitic Interface
  'gravitic_interface': {
    procs: [{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"recharge_debuff","effects":[{"attrib":"RechargeTime","scale":-0.1,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Gravitic Partial Core Conversion
  'gravitic_partial_core_conversion': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.25,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"recharge_debuff","effects":[{"attrib":"RechargeTime","scale":-0.1,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"movement_debuff","effects":[{"attrib":"JumpHeight","scale":-0.1,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"},{"attrib":"RunningSpeed","scale":-0.1,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"recovery_debuff","effects":[{"attrib":"Recovery","scale":-0.1,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Gravitic Partial Radial Conversion
  'gravitic_partial_radial_conversion': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.25,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"recharge_debuff","effects":[{"attrib":"RechargeTime","scale":-0.1,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"special_debuff","effects":[{"attrib":"Heal_Dmg","scale":-0.1,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"recovery_debuff","effects":[{"attrib":"Recovery","scale":-0.1,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Gravitic Radial Flawless Interface
  'gravitic_radial_flawless_interface': {
    procs: [{"chance":0.75,"ref":"unknown"},{"chance":0.75,"ref":"unknown"},{"chance":0.5,"ref":"unknown"}],
    procEffects: [{"name":"recharge_debuff","effects":[{"attrib":"RechargeTime","scale":-0.1,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"special_debuff","effects":[{"attrib":"Heal_Dmg","scale":-0.1,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"recovery_debuff","effects":[{"attrib":"Recovery","scale":-0.1,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Gravitic Radial Interface
  'gravitic_radial_interface': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"recharge_debuff","effects":[{"attrib":"RechargeTime","scale":-0.1,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"special_debuff","effects":[{"attrib":"Heal_Dmg","scale":-0.1,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Gravitic Total Core Conversion
  'gravitic_total_core_conversion': {
    procs: [{"chance":0.5,"ref":"unknown"},{"chance":0.5,"ref":"unknown"}],
    procEffects: [{"name":"recharge_debuff","effects":[{"attrib":"RechargeTime","scale":-0.1,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"movement_debuff","effects":[{"attrib":"JumpHeight","scale":-0.1,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"},{"attrib":"RunningSpeed","scale":-0.1,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Gravitic Total Radial Conversion
  'gravitic_total_radial_conversion': {
    procs: [{"chance":0.5,"ref":"unknown"},{"chance":0.5,"ref":"unknown"}],
    procEffects: [{"name":"recharge_debuff","effects":[{"attrib":"RechargeTime","scale":-0.1,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"special_debuff","effects":[{"attrib":"Heal_Dmg","scale":-0.1,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Paralytic Core Flawless Interface
  'paralytic_core_flawless_interface': {
    procs: [{"chance":0.75,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"defense_debuff","effects":[{"attrib":"Base_Defense","scale":-0.025,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"damage_debuff","effects":[{"attrib":"Smashing_Dmg","scale":-0.05,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Paralytic Core Interface
  'paralytic_core_interface': {
    procs: [{"chance":0.5,"ref":"unknown"}],
    procEffects: [{"name":"defense_debuff","effects":[{"attrib":"Base_Defense","scale":-0.025,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Paralytic Interface
  'paralytic_interface': {
    procs: [{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"defense_debuff","effects":[{"attrib":"Base_Defense","scale":-0.025,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Paralytic Partial Core Conversion
  'paralytic_partial_core_conversion': {
    procs: [{"chance":0.5,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"defense_debuff","effects":[{"attrib":"Base_Defense","scale":-0.025,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"damage_debuff","effects":[{"attrib":"Smashing_Dmg","scale":-0.05,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Paralytic Partial Radial Conversion
  'paralytic_partial_radial_conversion': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.5,"ref":"unknown"}],
    procEffects: [{"name":"defense_debuff","effects":[{"attrib":"Base_Defense","scale":-0.025,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"damage_debuff","effects":[{"attrib":"Smashing_Dmg","scale":-0.05,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Paralytic Radial Flawless Interface
  'paralytic_radial_flawless_interface': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.75,"ref":"unknown"}],
    procEffects: [{"name":"defense_debuff","effects":[{"attrib":"Base_Defense","scale":-0.025,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"damage_debuff","effects":[{"attrib":"Smashing_Dmg","scale":-0.05,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Paralytic Radial Interface
  'paralytic_radial_interface': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"defense_debuff","effects":[{"attrib":"Base_Defense","scale":-0.025,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]},{"name":"damage_debuff","effects":[{"attrib":"Smashing_Dmg","scale":-0.05,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Paralytic Total Core Conversion
  'paralytic_total_core_conversion': {
    procs: [{"chance":0.75,"ref":"unknown"}],
    procEffects: [{"name":"defense_debuff","effects":[{"attrib":"Base_Defense","scale":-0.025,"aspect":"Current","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Paralytic Total Radial Conversion
  'paralytic_total_radial_conversion': {
    procs: [{"chance":0.75,"ref":"unknown"}],
    procEffects: [{"name":"damage_debuff","effects":[{"attrib":"Smashing_Dmg","scale":-0.05,"aspect":"Strength","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Preemptive Core Flawless Interface
  'preemptive_core_flawless_interface': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.75,"ref":"unknown"}],
    procEffects: [{"name":"endurance_drain","effects":[{"attrib":"Recovery","scale":-0.05,"aspect":"Current","target":"AnyAffected","duration":"4.3 seconds"}]}],
  },
  // Preemptive Core Interface
  'preemptive_core_interface': {
    procs: [{"chance":0.5,"ref":"unknown"}],
    procEffects: [{"name":"endurance_drain","effects":[{"attrib":"Recovery","scale":-0.05,"aspect":"Current","target":"AnyAffected","duration":"4.3 seconds"}]}],
  },
  // Preemptive Interface
  'preemptive_interface': {
    procs: [{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"endurance_drain","effects":[{"attrib":"Recovery","scale":-0.05,"aspect":"Current","target":"AnyAffected","duration":"4.3 seconds"}]}],
  },
  // Preemptive Partial Core Conversion
  'preemptive_partial_core_conversion': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.5,"ref":"unknown"}],
    procEffects: [{"name":"endurance_drain","effects":[{"attrib":"Recovery","scale":-0.05,"aspect":"Current","target":"AnyAffected","duration":"4.3 seconds"}]}],
  },
  // Preemptive Partial Radial Conversion
  'preemptive_partial_radial_conversion': {
    procs: [{"chance":0.5,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"endurance_drain","effects":[{"attrib":"Recovery","scale":-0.05,"aspect":"Current","target":"AnyAffected","duration":"4.3 seconds"}]}],
  },
  // Preemptive Radial Flawless Interface
  'preemptive_radial_flawless_interface': {
    procs: [{"chance":0.75,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"endurance_drain","effects":[{"attrib":"Recovery","scale":-0.05,"aspect":"Current","target":"AnyAffected","duration":"4.3 seconds"}]}],
  },
  // Preemptive Radial Interface
  'preemptive_radial_interface': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"endurance_drain","effects":[{"attrib":"Recovery","scale":-0.05,"aspect":"Current","target":"AnyAffected","duration":"4.3 seconds"}]}],
  },
  // Preemptive Total Core Conversion
  'preemptive_total_core_conversion': {
    procs: [{"chance":0.75,"ref":"unknown"}],
    procEffects: [{"name":"endurance_drain","effects":[{"attrib":"Recovery","scale":-0.05,"aspect":"Current","target":"AnyAffected","duration":"4.3 seconds"}]}],
  },
  // Preemptive Total Radial Conversion
  'preemptive_total_radial_conversion': {
    procs: [{"chance":0.75,"ref":"unknown"}],
    procEffects: [{"name":"endurance_drain","effects":[{"attrib":"Recovery","scale":-0.05,"aspect":"Current","target":"AnyAffected","duration":"4.3 seconds"}]}],
  },
  // Reactive Core Flawless Interface
  'reactive_core_flawless_interface': {
    procs: [{"chance":0.75,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"resistance_debuff","effects":[{"attrib":"Smashing_Dmg","scale":-0.025,"aspect":"Resistance","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Reactive Core Interface
  'reactive_core_interface': {
    procs: [{"chance":0.5,"ref":"unknown"}],
    procEffects: [{"name":"resistance_debuff","effects":[{"attrib":"Smashing_Dmg","scale":-0.025,"aspect":"Resistance","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Reactive Interface
  'reactive_interface': {
    procs: [{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"resistance_debuff","effects":[{"attrib":"Smashing_Dmg","scale":-0.025,"aspect":"Resistance","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Reactive Partial Core Conversion
  'reactive_partial_core_conversion': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"resistance_debuff","effects":[{"attrib":"Smashing_Dmg","scale":-0.025,"aspect":"Resistance","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Reactive Partial Radial Conversion
  'reactive_partial_radial_conversion': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.5,"ref":"unknown"}],
    procEffects: [{"name":"resistance_debuff","effects":[{"attrib":"Smashing_Dmg","scale":-0.025,"aspect":"Resistance","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Reactive Radial Flawless Interface
  'reactive_radial_flawless_interface': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.75,"ref":"unknown"}],
    procEffects: [{"name":"resistance_debuff","effects":[{"attrib":"Smashing_Dmg","scale":-0.025,"aspect":"Resistance","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Reactive Radial Interface
  'reactive_radial_interface': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [{"name":"resistance_debuff","effects":[{"attrib":"Smashing_Dmg","scale":-0.025,"aspect":"Resistance","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Reactive Total Core Conversion
  'reactive_total_core_conversion': {
    procs: [{"chance":0.75,"ref":"unknown"}],
    procEffects: [{"name":"resistance_debuff","effects":[{"attrib":"Smashing_Dmg","scale":-0.025,"aspect":"Resistance","target":"AnyAffected","duration":"8.3 seconds"}]}],
  },
  // Reactive Total Radial Conversion
  'reactive_total_radial_conversion': {
    procs: [{"chance":0.75,"ref":"unknown"}],
    procEffects: [],
  },
  // Spectral Core Flawless Interface
  'spectral_core_flawless_interface': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.25,"ref":"unknown"}],
    procEffects: [],
  },
  // Spectral Core Interface
  'spectral_core_interface': {
    procs: [{"chance":0.15,"ref":"unknown"}],
    procEffects: [],
  },
  // Spectral Interface
  'spectral_interface': {
    procs: [{"chance":0.1,"ref":"unknown"}],
    procEffects: [],
  },
  // Spectral Partial Core Conversion
  'spectral_partial_core_conversion': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.15,"ref":"unknown"}],
    procEffects: [],
  },
  // Spectral Partial Radial Conversion
  'spectral_partial_radial_conversion': {
    procs: [{"chance":0.5,"ref":"unknown"},{"chance":0.1,"ref":"unknown"}],
    procEffects: [],
  },
  // Spectral Radial Flawless Interface
  'spectral_radial_flawless_interface': {
    procs: [{"chance":0.75,"ref":"unknown"},{"chance":0.125,"ref":"unknown"}],
    procEffects: [],
  },
  // Spectral Radial Interface
  'spectral_radial_interface': {
    procs: [{"chance":0.25,"ref":"unknown"},{"chance":0.1,"ref":"unknown"}],
    procEffects: [],
  },
  // Spectral Total Core Conversion
  'spectral_total_core_conversion': {
    procs: [{"chance":0.2,"ref":"unknown"}],
    procEffects: [],
  },
  // Spectral Total Radial Conversion
  'spectral_total_radial_conversion': {
    procs: [{"chance":0.75,"ref":"unknown"},{"chance":0.05,"ref":"unknown"}],
    procEffects: [],
  },
};

// ============================================
// LOOKUP FUNCTIONS
// ============================================

function normalizePowerId(powerId: string): string {
  return powerId.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/_+/g, '_');
}

export function getAlphaEffects(powerId: string): AlphaEffects | null {
  return ALPHA_EFFECTS[normalizePowerId(powerId)] || null;
}

export function getDestinyEffects(powerId: string): DestinyEffects | null {
  return DESTINY_EFFECTS[normalizePowerId(powerId)] || null;
}

export function getHybridEffects(powerId: string): HybridEffects | null {
  return HYBRID_EFFECTS[normalizePowerId(powerId)] || null;
}

export function getInterfaceEffects(powerId: string): InterfaceEffects | null {
  return INTERFACE_EFFECTS[normalizePowerId(powerId)] || null;
}
