/**
 * Incarnate System Data Layer
 *
 * Provides access to incarnate slot definitions, trees, and powers.
 * Slot indices are sourced from the bin-crawler export
 * (exported_powers/incarnate/<slot>/index.json), regenerated by
 * tools/bin-crawler/bin_crawler/export_powers.py against the live HC
 * .pigg archives.
 */

import { getPowerIconPath } from '@/utils/power-icons';
import type {
  IncarnateSlotId,
  IncarnateTier,
  IncarnateSlotDefinition,
  IncarnateTree,
  IncarnatePower,
} from '@/types';
import {
  INCARNATE_SLOT_ORDER,
  inferTierFromPowerName,
  inferBranchFromPowerName,
} from '@/types';
import {
  getSlotColor,
  getTreeDescription,
} from './incarnate-registry';

// ============================================
// RAW DATA IMPORTS
// ============================================

// Import slot index files (bin-crawler shape)
import alphaIndex from '../../exported_powers/incarnate/alpha/index.json';
import judgementIndex from '../../exported_powers/incarnate/judgement/index.json';
import interfaceIndex from '../../exported_powers/incarnate/interface/index.json';
import destinyIndex from '../../exported_powers/incarnate/destiny/index.json';
import loreIndex from '../../exported_powers/incarnate/lore/index.json';
import hybridIndex from '../../exported_powers/incarnate/hybrid/index.json';

// Bin-crawler index shape: `powers` is the full-name array; the parallel
// `power_display_names` and `power_short_helps` arrays are populated
// alongside it by export_powers.py.
interface RawSlotIndex {
  key: string;             // e.g. "Incarnate.Alpha"
  display_name: string;
  icon: string;
  powers: string[];
  power_display_names: string[];
  power_short_helps: string[];
}

// Map slot IDs to their raw data
const RAW_SLOT_INDICES: Record<IncarnateSlotId, RawSlotIndex> = {
  alpha: alphaIndex as RawSlotIndex,
  judgement: judgementIndex as RawSlotIndex,
  interface: interfaceIndex as RawSlotIndex,
  destiny: destinyIndex as RawSlotIndex,
  lore: loreIndex as RawSlotIndex,
  hybrid: hybridIndex as RawSlotIndex,
};


// ============================================
// DATA PROCESSING
// ============================================

/**
 * Lore pet names where the tree ID doesn't match the first word of the power name.
 * Maps the multi-word prefix (lowercase) to the correct tree ID used in icon filenames.
 */
const LORE_NAME_PREFIX_TO_TREE: Record<string, string> = {
  'polar_lights': 'lights',
  'robotic_drones': 'drones',
  'storm_elemental': 'elementals',
  'phantom': 'phantoms',
  'banished_pantheon': 'banished',
  'knives_of_vengeance': 'knives',
  'talons_of_vengeance': 'talons',
};

/**
 * Parse a power full name to extract tree and power info
 * e.g., "Incarnate.Alpha.Musculature_Core_Paragon" -> { tree: "musculature", name: "Core Paragon" }
 */
function parsePowerName(fullName: string): { tree: string; powerName: string } {
  const parts = fullName.split('.');
  const lastPart = parts[parts.length - 1]; // e.g., "Musculature_Core_Paragon"
  const lowerPart = lastPart.toLowerCase();

  // Check multi-word prefixes first (for lore pets like Polar_Lights, Robotic_Drones, etc.)
  for (const [prefix, treeId] of Object.entries(LORE_NAME_PREFIX_TO_TREE)) {
    if (lowerPart.startsWith(prefix + '_')) {
      const powerName = lastPart.slice(prefix.length + 1);
      return { tree: treeId, powerName };
    }
  }

  const underscoreParts = lastPart.split('_');
  const tree = underscoreParts[0].toLowerCase();
  const powerName = underscoreParts.slice(1).join('_');
  return { tree, powerName };
}

/**
 * Get icon filename from power display name and tier
 */
function getIconFromTier(slotId: IncarnateSlotId, treeId: string, tier: IncarnateTier): string {
  const tierSuffix = tier === 'common' ? 'common' :
                     tier === 'uncommon' ? 'uncommon' :
                     tier === 'rare' ? 'rare' : 'veryrare';
  return `incarnate_${slotId}_${treeId}_${tierSuffix}.png`;
}

/**
 * Build the slot definition from raw data
 */
function buildSlotDefinition(slotId: IncarnateSlotId): IncarnateSlotDefinition {
  const raw = RAW_SLOT_INDICES[slotId];
  const treeMap = new Map<string, IncarnatePower[]>();

  // Process each power
  for (let i = 0; i < raw.powers.length; i++) {
    const fullName = raw.powers[i];
    const displayName = raw.power_display_names[i];
    const shortHelp = raw.power_short_helps?.[i] || '';

    const { tree } = parsePowerName(fullName);
    const tier = inferTierFromPowerName(displayName);
    const branch = inferBranchFromPowerName(displayName);
    const icon = getIconFromTier(slotId, tree, tier);

    const power: IncarnatePower = {
      id: fullName.split('.').pop()?.toLowerCase() || '',
      fullName,
      displayName,
      shortHelp,
      displayHelp: shortHelp, // Will be loaded on demand from individual power files
      icon,
      tier,
      branch,
      treeId: tree,
      slotId,
      powerType: 'Auto', // Most incarnate powers are auto
    };

    if (!treeMap.has(tree)) {
      treeMap.set(tree, []);
    }
    treeMap.get(tree)!.push(power);
  }

  // Build trees from the map
  const trees: IncarnateTree[] = [];
  for (const [treeId, powers] of treeMap) {
    trees.push({
      id: treeId,
      name: treeId.charAt(0).toUpperCase() + treeId.slice(1),
      description: getTreeDescription(slotId, treeId),
      powers: powers.sort((a, b) => {
        // Sort by tier, then by branch
        const tierOrder = ['common', 'uncommon', 'rare', 'veryrare'];
        const tierDiff = tierOrder.indexOf(a.tier) - tierOrder.indexOf(b.tier);
        if (tierDiff !== 0) return tierDiff;

        const branchOrder = ['base', 'core', 'radial'];
        return branchOrder.indexOf(a.branch) - branchOrder.indexOf(b.branch);
      }),
    });
  }

  // Sort trees alphabetically
  trees.sort((a, b) => a.name.localeCompare(b.name));

  return {
    id: slotId,
    // The bin-crawler index has `key` like "Incarnate.Alpha" — use the
    // suffix as the slot's internal name (matches the old shape's `name`).
    name: raw.key.split('.').pop() || raw.display_name,
    displayName: raw.display_name,
    icon: raw.icon,
    color: getSlotColor(slotId),
    trees,
  };
}

// ============================================
// CACHED DATA
// ============================================

let _slotDefinitions: IncarnateSlotDefinition[] | null = null;
let _slotMap: Map<IncarnateSlotId, IncarnateSlotDefinition> | null = null;

function ensureDataLoaded(): void {
  if (_slotDefinitions === null) {
    _slotDefinitions = INCARNATE_SLOT_ORDER.map(buildSlotDefinition);
    _slotMap = new Map(_slotDefinitions.map(s => [s.id, s]));
  }
}

// ============================================
// PUBLIC API
// ============================================

/**
 * Get all incarnate slot definitions
 */
export function getAllIncarnateSlots(): IncarnateSlotDefinition[] {
  ensureDataLoaded();
  return _slotDefinitions!;
}

/**
 * Get a specific incarnate slot definition
 */
export function getIncarnateSlot(slotId: IncarnateSlotId): IncarnateSlotDefinition | undefined {
  ensureDataLoaded();
  return _slotMap!.get(slotId);
}

/**
 * Get all trees for a slot
 */
export function getIncarnateTrees(slotId: IncarnateSlotId): IncarnateTree[] {
  const slot = getIncarnateSlot(slotId);
  return slot?.trees || [];
}

/**
 * Get a specific tree within a slot
 */
export function getIncarnateTree(slotId: IncarnateSlotId, treeId: string): IncarnateTree | undefined {
  const trees = getIncarnateTrees(slotId);
  return trees.find(t => t.id === treeId);
}

/**
 * Get all powers for a tree
 */
export function getIncarnatePowersForTree(slotId: IncarnateSlotId, treeId: string): IncarnatePower[] {
  const tree = getIncarnateTree(slotId, treeId);
  return tree?.powers || [];
}

/**
 * Get powers by tier for a tree
 */
export function getIncarnatePowersByTier(
  slotId: IncarnateSlotId,
  treeId: string,
  tier: IncarnateTier
): IncarnatePower[] {
  const powers = getIncarnatePowersForTree(slotId, treeId);
  return powers.filter(p => p.tier === tier);
}

/**
 * Find a specific power by ID
 */
export function getIncarnatePower(
  slotId: IncarnateSlotId,
  powerId: string
): IncarnatePower | undefined {
  const slot = getIncarnateSlot(slotId);
  if (!slot) return undefined;

  // Exact match on id or fullName
  for (const tree of slot.trees) {
    const power = tree.powers.find(p => p.id === powerId || p.fullName === powerId);
    if (power) return power;
  }

  // Case-insensitive fallback
  const lowerPowerId = powerId.toLowerCase();
  for (const tree of slot.trees) {
    const power = tree.powers.find(
      p => p.id === lowerPowerId || p.fullName?.toLowerCase() === lowerPowerId
    );
    if (power) return power;
  }

  // Last-segment fallback: extract final segment and match against id
  const lastSegment = powerId.split('.').pop()?.toLowerCase();
  if (lastSegment) {
    for (const tree of slot.trees) {
      const power = tree.powers.find(p => p.id === lastSegment);
      if (power) return power;
    }
  }

  // Display name fallback: normalize underscores to spaces and match
  const normalizedName = lastSegment?.replace(/_/g, ' ');
  if (normalizedName) {
    for (const tree of slot.trees) {
      const power = tree.powers.find(
        p => p.displayName.toLowerCase() === normalizedName
      );
      if (power) return power;
    }
  }

  return undefined;
}

/**
 * Get the slot icon path (uses the blank/empty slot icon)
 */
export function getIncarnateSlotIconPath(slotId: IncarnateSlotId): string {
  return getPowerIconPath(`incarnate_${slotId}_blank.png`);
}
